include('incl/xboole_0.ax').
include('incl/xboole_1.ax').
include('incl/enumset1.ax').
include('incl/zfmisc_1.ax').
include('incl/subset_1.ax').
include('incl/setfam_1.ax').
include('incl/relat_1.ax').
include('incl/funct_1.ax').
include('incl/ordinal1.ax').
include('incl/wellord1.ax').
include('incl/relset_1.ax').
include('incl/mcart_1.ax').
include('incl/wellord2.ax').
include('incl/funct_2.ax').
include('incl/finset_1.ax').
include('incl/pre_topc.ax').
include('incl/orders_2.ax').
include('incl/lattices.ax').
include('incl/tops_1.ax').
include('incl/tops_2.ax').
include('incl/compts_1.ax').
include('incl/connsp_2.ax').
include('incl/filter_1.ax').
fof(cc1_lattice3, axiom,  (! [A] :  (l1_orders_2(A) =>  (v1_lattice3(A) =>  ~ (v2_struct_0(A)) ) ) ) ).
fof(cc2_lattice3, axiom,  (! [A] :  (l1_orders_2(A) =>  (v2_lattice3(A) =>  ~ (v2_struct_0(A)) ) ) ) ).
fof(commutativity_k12_lattice3, axiom,  (! [A, B, C] :  ( ( (v5_orders_2(A) &  (v2_lattice3(A) & l1_orders_2(A)) )  &  (m1_subset_1(B, u1_struct_0(A)) & m1_subset_1(C, u1_struct_0(A))) )  => k12_lattice3(A, B, C)=k12_lattice3(A, C, B)) ) ).
fof(commutativity_k13_lattice3, axiom,  (! [A, B, C] :  ( ( (v5_orders_2(A) &  (v1_lattice3(A) & l1_orders_2(A)) )  &  (m1_subset_1(B, u1_struct_0(A)) & m1_subset_1(C, u1_struct_0(A))) )  => k13_lattice3(A, B, C)=k13_lattice3(A, C, B)) ) ).
fof(d10_lattice3, axiom,  (! [A] :  (l1_orders_2(A) =>  (v1_lattice3(A) <=>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (? [D] :  (m1_subset_1(D, u1_struct_0(A)) &  (r1_orders_2(A, B, D) &  (r1_orders_2(A, C, D) &  (! [E] :  (m1_subset_1(E, u1_struct_0(A)) =>  ( (r1_orders_2(A, B, E) & r1_orders_2(A, C, E))  => r1_orders_2(A, D, E)) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(d11_lattice3, axiom,  (! [A] :  (l1_orders_2(A) =>  (v2_lattice3(A) <=>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (? [D] :  (m1_subset_1(D, u1_struct_0(A)) &  (r1_orders_2(A, D, B) &  (r1_orders_2(A, D, C) &  (! [E] :  (m1_subset_1(E, u1_struct_0(A)) =>  ( (r1_orders_2(A, E, B) & r1_orders_2(A, E, C))  => r1_orders_2(A, E, D)) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(d12_lattice3, axiom,  (! [A] :  (l1_orders_2(A) =>  (v3_lattice3(A) <=>  (! [B] :  (? [C] :  (m1_subset_1(C, u1_struct_0(A)) &  (r2_lattice3(A, B, C) &  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (r2_lattice3(A, B, D) => r1_orders_2(A, C, D)) ) ) ) ) ) ) ) ) ) ).
fof(d13_lattice3, axiom,  (! [A] :  (l1_orders_2(A) =>  (v5_orders_2(A) =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  ( (? [D] :  (m1_subset_1(D, u1_struct_0(A)) &  (r1_orders_2(A, B, D) &  (r1_orders_2(A, C, D) &  (! [E] :  (m1_subset_1(E, u1_struct_0(A)) =>  ( (r1_orders_2(A, B, E) & r1_orders_2(A, C, E))  => r1_orders_2(A, D, E)) ) ) ) ) ) )  =>  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (D=k10_lattice3(A, B, C) <=>  (r1_orders_2(A, B, D) &  (r1_orders_2(A, C, D) &  (! [E] :  (m1_subset_1(E, u1_struct_0(A)) =>  ( (r1_orders_2(A, B, E) & r1_orders_2(A, C, E))  => r1_orders_2(A, D, E)) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(d14_lattice3, axiom,  (! [A] :  (l1_orders_2(A) =>  (v5_orders_2(A) =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  ( (? [D] :  (m1_subset_1(D, u1_struct_0(A)) &  (r1_orders_2(A, D, B) &  (r1_orders_2(A, D, C) &  (! [E] :  (m1_subset_1(E, u1_struct_0(A)) =>  ( (r1_orders_2(A, E, B) & r1_orders_2(A, E, C))  => r1_orders_2(A, E, D)) ) ) ) ) ) )  =>  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (D=k11_lattice3(A, B, C) <=>  (r1_orders_2(A, D, B) &  (r1_orders_2(A, D, C) &  (! [E] :  (m1_subset_1(E, u1_struct_0(A)) =>  ( (r1_orders_2(A, E, B) & r1_orders_2(A, E, C))  => r1_orders_2(A, E, D)) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(d16_lattice3, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l3_lattices(A))  =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (r3_lattice3(A, B, C) <=>  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (r2_hidden(D, C) => r1_lattices(A, B, D)) ) ) ) ) ) ) ) ) ).
fof(d17_lattice3, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l3_lattices(A))  =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (r4_lattice3(A, B, C) <=>  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (r2_hidden(D, C) => r1_lattices(A, D, B)) ) ) ) ) ) ) ) ) ).
fof(d18_lattice3, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l3_lattices(A))  =>  (v4_lattice3(A) <=>  (! [B] :  (? [C] :  (m1_subset_1(C, u1_struct_0(A)) &  (r4_lattice3(A, C, B) &  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (r4_lattice3(A, D, B) => r1_lattices(A, C, D)) ) ) ) ) ) ) ) ) ) ).
fof(d19_lattice3, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l3_lattices(A))  =>  (v5_lattice3(A) <=>  (! [B] :  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (! [E] :  (m1_subset_1(E, u1_struct_0(A)) =>  ( (r4_lattice3(A, C, B) &  ( (! [F] :  (m1_subset_1(F, u1_struct_0(A)) =>  (r4_lattice3(A, F, B) => r1_lattices(A, C, F)) ) )  &  (r4_lattice3(A, E, a_3_0_lattice3(A, B, D)) &  (! [F] :  (m1_subset_1(F, u1_struct_0(A)) =>  (r4_lattice3(A, F, a_3_0_lattice3(A, B, D)) => r1_lattices(A, E, F)) ) ) ) ) )  => r1_lattices(A, k2_lattices(A, D, C), E)) ) ) ) ) ) ) ) ) ) ) ).
fof(d1_lattice3, axiom,  (! [A] :  (! [B] :  ( (v3_lattices(B) & l3_lattices(B))  =>  (B=k1_lattice3(A) <=>  (u1_struct_0(B)=k9_setfam_1(A) &  (! [C] :  (m1_subset_1(C, k1_zfmisc_1(A)) =>  (! [D] :  (m1_subset_1(D, k1_zfmisc_1(A)) =>  (k1_binop_1(u2_lattices(B), C, D)=k4_subset_1(A, C, D) & k1_binop_1(u1_lattices(B), C, D)=k9_subset_1(A, C, D)) ) ) ) ) ) ) ) ) ) ).
fof(d20_lattice3, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l3_lattices(A))  =>  (v6_lattice3(A) <=>  (! [B] :  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (! [E] :  (m1_subset_1(E, u1_struct_0(A)) =>  ( (r3_lattice3(A, C, B) &  ( (! [F] :  (m1_subset_1(F, u1_struct_0(A)) =>  (r3_lattice3(A, F, B) => r1_lattices(A, F, C)) ) )  &  (r3_lattice3(A, E, a_3_1_lattice3(A, B, D)) &  (! [F] :  (m1_subset_1(F, u1_struct_0(A)) =>  (r3_lattice3(A, F, a_3_1_lattice3(A, B, D)) => r1_lattices(A, F, E)) ) ) ) ) )  => r1_lattices(A, E, k1_lattices(A, D, C))) ) ) ) ) ) ) ) ) ) ) ).
fof(d21_lattice3, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l3_lattices(A))  =>  ( ( ~ (v2_struct_0(A))  &  (v10_lattices(A) &  (v4_lattice3(A) & l3_lattices(A)) ) )  =>  (! [B] :  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (C=k15_lattice3(A, B) <=>  (r4_lattice3(A, C, B) &  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (r4_lattice3(A, D, B) => r1_lattices(A, C, D)) ) ) ) ) ) ) ) ) ) ) ).
fof(d22_lattice3, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l3_lattices(A))  =>  (! [B] : k16_lattice3(A, B)=k15_lattice3(A, a_2_1_lattice3(A, B))) ) ) ).
fof(d2_lattice3, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v10_lattices(A) & l3_lattices(A)) )  => k3_lattice3(A)=g1_orders_2(u1_struct_0(A), k2_lattice3(A))) ) ).
fof(d3_lattice3, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v10_lattices(A) & l3_lattices(A)) )  =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) => k4_lattice3(A, B)=B) ) ) ) ).
fof(d4_lattice3, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v10_lattices(A) & l3_lattices(A)) )  =>  (! [B] :  (m1_subset_1(B, u1_struct_0(k3_lattice3(A))) => k5_lattice3(A, B)=B) ) ) ) ).
fof(d4_lattices, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l2_lattices(A))  =>  (v4_lattices(A) <=>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) => k1_lattices(A, B, C)=k1_lattices(A, C, B)) ) ) ) ) ) ) ).
fof(d5_lattice3, axiom,  (! [A] :  (l1_orders_2(A) => k7_lattice3(A)=g1_orders_2(u1_struct_0(A), k3_relset_1(u1_struct_0(A), u1_struct_0(A), u1_orders_2(A)))) ) ).
fof(d6_lattice3, axiom,  (! [A] :  (l1_orders_2(A) =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) => k8_lattice3(A, B)=B) ) ) ) ).
fof(d6_lattices, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l1_lattices(A))  =>  (v6_lattices(A) <=>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) => k2_lattices(A, B, C)=k2_lattices(A, C, B)) ) ) ) ) ) ) ).
fof(d7_lattice3, axiom,  (! [A] :  (l1_orders_2(A) =>  (! [B] :  (m1_subset_1(B, u1_struct_0(k7_lattice3(A))) => k9_lattice3(A, B)=B) ) ) ) ).
fof(d8_lattice3, axiom,  (! [A] :  (l1_orders_2(A) =>  (! [B] :  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (r1_lattice3(A, B, C) <=>  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (r2_hidden(D, B) => r1_orders_2(A, C, D)) ) ) ) ) ) ) ) ) ).
fof(d9_lattice3, axiom,  (! [A] :  (l1_orders_2(A) =>  (! [B] :  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (r2_lattice3(A, B, C) <=>  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (r2_hidden(D, B) => r1_orders_2(A, D, C)) ) ) ) ) ) ) ) ) ).
fof(dt_k10_lattice3, axiom,  (! [A, B, C] :  ( (l1_orders_2(A) &  (m1_subset_1(B, u1_struct_0(A)) & m1_subset_1(C, u1_struct_0(A))) )  => m1_subset_1(k10_lattice3(A, B, C), u1_struct_0(A))) ) ).
fof(dt_k11_lattice3, axiom,  (! [A, B, C] :  ( (l1_orders_2(A) &  (m1_subset_1(B, u1_struct_0(A)) & m1_subset_1(C, u1_struct_0(A))) )  => m1_subset_1(k11_lattice3(A, B, C), u1_struct_0(A))) ) ).
fof(dt_k12_lattice3, axiom,  (! [A, B, C] :  ( ( (v5_orders_2(A) &  (v2_lattice3(A) & l1_orders_2(A)) )  &  (m1_subset_1(B, u1_struct_0(A)) & m1_subset_1(C, u1_struct_0(A))) )  => m1_subset_1(k12_lattice3(A, B, C), u1_struct_0(A))) ) ).
fof(dt_k13_lattice3, axiom,  (! [A, B, C] :  ( ( (v5_orders_2(A) &  (v1_lattice3(A) & l1_orders_2(A)) )  &  (m1_subset_1(B, u1_struct_0(A)) & m1_subset_1(C, u1_struct_0(A))) )  => m1_subset_1(k13_lattice3(A, B, C), u1_struct_0(A))) ) ).
fof(dt_k15_lattice3, axiom,  (! [A, B] :  ( ( ~ (v2_struct_0(A))  & l3_lattices(A))  => m1_subset_1(k15_lattice3(A, B), u1_struct_0(A))) ) ).
fof(dt_k16_lattice3, axiom,  (! [A, B] :  ( ( ~ (v2_struct_0(A))  & l3_lattices(A))  => m1_subset_1(k16_lattice3(A, B), u1_struct_0(A))) ) ).
fof(dt_k1_lattice3, axiom,  (! [A] :  (v3_lattices(k1_lattice3(A)) & l3_lattices(k1_lattice3(A))) ) ).
fof(dt_k2_lattice3, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v10_lattices(A) & l3_lattices(A)) )  =>  (v1_partfun1(k2_lattice3(A), u1_struct_0(A)) &  (v1_relat_2(k2_lattice3(A)) &  (v4_relat_2(k2_lattice3(A)) &  (v8_relat_2(k2_lattice3(A)) & m1_subset_1(k2_lattice3(A), k1_zfmisc_1(k2_zfmisc_1(u1_struct_0(A), u1_struct_0(A))))) ) ) ) ) ) ).
fof(dt_k3_lattice3, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v10_lattices(A) & l3_lattices(A)) )  =>  (v1_orders_2(k3_lattice3(A)) &  (v3_orders_2(k3_lattice3(A)) &  (v4_orders_2(k3_lattice3(A)) &  (v5_orders_2(k3_lattice3(A)) & l1_orders_2(k3_lattice3(A))) ) ) ) ) ) ).
fof(dt_k4_lattice3, axiom,  (! [A, B] :  ( ( ( ~ (v2_struct_0(A))  &  (v10_lattices(A) & l3_lattices(A)) )  & m1_subset_1(B, u1_struct_0(A)))  => m1_subset_1(k4_lattice3(A, B), u1_struct_0(k3_lattice3(A)))) ) ).
fof(dt_k5_lattice3, axiom,  (! [A, B] :  ( ( ( ~ (v2_struct_0(A))  &  (v10_lattices(A) & l3_lattices(A)) )  & m1_subset_1(B, u1_struct_0(k3_lattice3(A))))  => m1_subset_1(k5_lattice3(A, B), u1_struct_0(A))) ) ).
fof(dt_k6_lattice3, axiom,  (! [A, B] :  ( (v1_partfun1(B, A) &  (v1_relat_2(B) &  (v4_relat_2(B) &  (v8_relat_2(B) & m1_subset_1(B, k1_zfmisc_1(k2_zfmisc_1(A, A)))) ) ) )  =>  (v1_partfun1(k6_lattice3(A, B), A) &  (v1_relat_2(k6_lattice3(A, B)) &  (v4_relat_2(k6_lattice3(A, B)) &  (v8_relat_2(k6_lattice3(A, B)) & m1_subset_1(k6_lattice3(A, B), k1_zfmisc_1(k2_zfmisc_1(A, A)))) ) ) ) ) ) ).
fof(dt_k7_lattice3, axiom,  (! [A] :  (l1_orders_2(A) =>  (v1_orders_2(k7_lattice3(A)) & l1_orders_2(k7_lattice3(A))) ) ) ).
fof(dt_k8_lattice3, axiom,  (! [A, B] :  ( (l1_orders_2(A) & m1_subset_1(B, u1_struct_0(A)))  => m1_subset_1(k8_lattice3(A, B), u1_struct_0(k7_lattice3(A)))) ) ).
fof(dt_k9_lattice3, axiom,  (! [A, B] :  ( (l1_orders_2(A) & m1_subset_1(B, u1_struct_0(k7_lattice3(A))))  => m1_subset_1(k9_lattice3(A, B), u1_struct_0(A))) ) ).
fof(fc1_lattice3, axiom,  (! [A] :  ( ~ (v2_struct_0(k1_lattice3(A)))  & v3_lattices(k1_lattice3(A))) ) ).
fof(fc2_lattice3, axiom,  (! [A] :  (v3_lattices(k1_lattice3(A)) & v10_lattices(k1_lattice3(A))) ) ).
fof(fc3_lattice3, axiom,  (! [A] :  (v3_lattices(k1_lattice3(A)) & v17_lattices(k1_lattice3(A))) ) ).
fof(fc4_lattice3, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v10_lattices(A) & l3_lattices(A)) )  =>  ( ~ (v2_struct_0(k3_lattice3(A)))  &  (v1_orders_2(k3_lattice3(A)) &  (v3_orders_2(k3_lattice3(A)) &  (v4_orders_2(k3_lattice3(A)) & v5_orders_2(k3_lattice3(A))) ) ) ) ) ) ).
fof(fc5_lattice3, axiom,  (! [A] :  ( (v3_orders_2(A) &  (v4_orders_2(A) &  (v5_orders_2(A) & l1_orders_2(A)) ) )  =>  (v1_orders_2(k7_lattice3(A)) &  (v3_orders_2(k7_lattice3(A)) &  (v4_orders_2(k7_lattice3(A)) & v5_orders_2(k7_lattice3(A))) ) ) ) ) ).
fof(fc6_lattice3, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l1_orders_2(A))  =>  ( ~ (v2_struct_0(k7_lattice3(A)))  & v1_orders_2(k7_lattice3(A))) ) ) ).
fof(fc7_lattice3, axiom,  (! [A] :  (v3_lattices(k1_lattice3(A)) & v4_lattice3(k1_lattice3(A))) ) ).
fof(fraenkel_a_1_0_lattice3, axiom,  (! [A, B] :  ( ( ~ (v2_struct_0(B))  &  (v10_lattices(B) & l3_lattices(B)) )  =>  (r2_hidden(A, a_1_0_lattice3(B)) <=>  (? [C, D] :  ( (m1_subset_1(C, u1_struct_0(B)) & m1_subset_1(D, u1_struct_0(B)))  &  (A=k9_filter_1(B, B, C, D) & r3_lattices(B, C, D)) ) ) ) ) ) ).
fof(fraenkel_a_1_2_lattice3, axiom,  (! [A, B] :  ( ( ~ (v2_struct_0(B))  &  (v3_lattices(B) &  (v10_lattices(B) & l3_lattices(B)) ) )  =>  (r2_hidden(A, a_1_2_lattice3(B)) <=>  (? [C, D] :  ( (m1_subset_1(C, u1_struct_0(B)) & m1_subset_1(D, u1_struct_0(B)))  &  (A=k9_filter_1(B, B, C, D) & r3_lattices(B, C, D)) ) ) ) ) ) ).
fof(fraenkel_a_1_3_lattice3, axiom,  (! [A, B] :  ( ( ~ (v2_struct_0(B))  &  (v10_lattices(B) & l3_lattices(B)) )  =>  (r2_hidden(A, a_1_3_lattice3(B)) <=>  (? [C, D] :  ( (m1_subset_1(C, u1_struct_0(k1_lattice2(B))) & m1_subset_1(D, u1_struct_0(k1_lattice2(B))))  &  (A=k9_filter_1(k1_lattice2(B), k1_lattice2(B), C, D) & r3_lattices(k1_lattice2(B), C, D)) ) ) ) ) ) ).
fof(fraenkel_a_2_0_lattice3, axiom,  (! [A, B, C] :  ( ( ~ (v2_struct_0(C))  &  (v10_lattices(C) &  (v17_lattices(C) & l3_lattices(C)) ) )  =>  (r2_hidden(A, a_2_0_lattice3(B, C)) <=>  (? [D] :  (m1_subset_1(D, u1_struct_0(C)) &  (A=k7_lattices(C, D) & r2_hidden(D, B)) ) ) ) ) ) ).
fof(fraenkel_a_2_1_lattice3, axiom,  (! [A, B, C] :  ( ( ~ (v2_struct_0(B))  & l3_lattices(B))  =>  (r2_hidden(A, a_2_1_lattice3(B, C)) <=>  (? [D] :  (m1_subset_1(D, u1_struct_0(B)) &  (A=D & r3_lattice3(B, D, C)) ) ) ) ) ) ).
fof(fraenkel_a_2_8_lattice3, axiom,  (! [A, B, C] :  (r2_hidden(A, a_2_8_lattice3(B, C)) <=>  (? [D] :  (m1_subset_1(D, u1_struct_0(k1_lattice3(B))) &  (A=k7_lattices(k1_lattice3(B), D) & r2_hidden(D, C)) ) ) ) ) ).
fof(fraenkel_a_2_9_lattice3, axiom,  (! [A, B, C] :  ( ( ~ (v2_struct_0(B))  &  (v10_lattices(B) &  (v4_lattice3(B) & l3_lattices(B)) ) )  =>  (r2_hidden(A, a_2_9_lattice3(B, C)) <=>  (? [D] :  (m1_subset_1(D, u1_struct_0(B)) &  (A=D & r3_lattice3(B, D, C)) ) ) ) ) ) ).
fof(fraenkel_a_3_0_lattice3, axiom,  (! [A, B, C, D] :  ( ( ( ~ (v2_struct_0(B))  & l3_lattices(B))  & m1_subset_1(D, u1_struct_0(B)))  =>  (r2_hidden(A, a_3_0_lattice3(B, C, D)) <=>  (? [E] :  (m1_subset_1(E, u1_struct_0(B)) &  (A=k2_lattices(B, D, E) & r2_hidden(E, C)) ) ) ) ) ) ).
fof(fraenkel_a_3_11_lattice3, axiom,  (! [A, B, C, D] :  ( ( ( ~ (v2_struct_0(B))  & l1_orders_2(B))  &  (m1_subset_1(C, u1_struct_0(B)) & m1_subset_1(D, u1_struct_0(B))) )  =>  (r2_hidden(A, a_3_11_lattice3(B, C, D)) <=>  (? [E] :  (m1_subset_1(E, u1_struct_0(B)) &  (A=E &  (r1_orders_2(B, E, C) & r1_orders_2(B, E, D)) ) ) ) ) ) ) ).
fof(fraenkel_a_3_12_lattice3, axiom,  (! [A, B, C, D] :  (m1_subset_1(D, u1_struct_0(k1_lattice3(B))) =>  (r2_hidden(A, a_3_12_lattice3(B, C, D)) <=>  (? [E] :  (m1_subset_1(E, u1_struct_0(k1_lattice3(B))) &  (A=k2_lattices(k1_lattice3(B), D, E) & r2_hidden(E, C)) ) ) ) ) ) ).
fof(fraenkel_a_3_13_lattice3, axiom,  (! [A, B, C, D] :  (m1_subset_1(D, u1_struct_0(k1_lattice3(B))) =>  (r2_hidden(A, a_3_13_lattice3(B, C, D)) <=>  (? [E] :  (m1_subset_1(E, u1_struct_0(k1_lattice3(B))) &  (A=k4_lattices(k1_lattice3(B), D, E) & r2_hidden(E, C)) ) ) ) ) ) ).
fof(fraenkel_a_3_14_lattice3, axiom,  (! [A, B, C, D] :  (m1_subset_1(D, u1_struct_0(k1_lattice3(B))) =>  (r2_hidden(A, a_3_14_lattice3(B, C, D)) <=>  (? [E] :  (m1_subset_1(E, u1_struct_0(k1_lattice3(B))) &  (A=k1_lattices(k1_lattice3(B), D, E) & r2_hidden(E, C)) ) ) ) ) ) ).
fof(fraenkel_a_3_15_lattice3, axiom,  (! [A, B, C, D] :  (m1_subset_1(D, u1_struct_0(k1_lattice3(B))) =>  (r2_hidden(A, a_3_15_lattice3(B, C, D)) <=>  (? [E] :  (m1_subset_1(E, u1_struct_0(k1_lattice3(B))) &  (A=k3_lattices(k1_lattice3(B), D, E) & r2_hidden(E, C)) ) ) ) ) ) ).
fof(fraenkel_a_3_16_lattice3, axiom,  (! [A, B, C, D] :  (m1_subset_1(D, u1_struct_0(k1_lattice3(B))) =>  (r2_hidden(A, a_3_16_lattice3(B, C, D)) <=>  (? [E] :  (m1_subset_1(E, u1_struct_0(k1_lattice3(B))) &  (A=k7_lattices(k1_lattice3(B), E) & r2_hidden(E, a_3_15_lattice3(B, C, D))) ) ) ) ) ) ).
fof(fraenkel_a_3_17_lattice3, axiom,  (! [A, B, C, D] :  (m1_subset_1(D, u1_struct_0(k1_lattice3(B))) =>  (r2_hidden(A, a_3_17_lattice3(B, C, D)) <=>  (? [E] :  (m1_subset_1(E, u1_struct_0(k1_lattice3(B))) &  (A=k4_lattices(k1_lattice3(B), k7_lattices(k1_lattice3(B), D), E) & r2_hidden(E, a_2_8_lattice3(B, C))) ) ) ) ) ) ).
fof(fraenkel_a_3_18_lattice3, axiom,  (! [A, B, C, D] :  ( ( ( ~ (v2_struct_0(B))  &  (v10_lattices(B) &  (v4_lattice3(B) & l3_lattices(B)) ) )  & m1_subset_1(D, u1_struct_0(B)))  =>  (r2_hidden(A, a_3_18_lattice3(B, C, D)) <=>  (? [E] :  (m1_subset_1(E, u1_struct_0(B)) &  (A=k2_lattices(B, D, E) & r2_hidden(E, C)) ) ) ) ) ) ).
fof(fraenkel_a_3_1_lattice3, axiom,  (! [A, B, C, D] :  ( ( ( ~ (v2_struct_0(B))  & l3_lattices(B))  & m1_subset_1(D, u1_struct_0(B)))  =>  (r2_hidden(A, a_3_1_lattice3(B, C, D)) <=>  (? [E] :  (m1_subset_1(E, u1_struct_0(B)) &  (A=k1_lattices(B, D, E) & r2_hidden(E, C)) ) ) ) ) ) ).
fof(fraenkel_a_3_2_lattice3, axiom,  (! [A, B, C, D] :  ( ( ( ~ (v2_struct_0(B))  &  (v10_lattices(B) &  (v4_lattice3(B) & l3_lattices(B)) ) )  & m1_subset_1(C, u1_struct_0(B)))  =>  (r2_hidden(A, a_3_2_lattice3(B, C, D)) <=>  (? [E] :  (m1_subset_1(E, u1_struct_0(B)) &  (A=k4_lattices(B, C, E) & r2_hidden(E, D)) ) ) ) ) ) ).
fof(fraenkel_a_3_3_lattice3, axiom,  (! [A, B, C, D] :  ( ( ( ~ (v2_struct_0(B))  &  (v10_lattices(B) &  (v4_lattice3(B) & l3_lattices(B)) ) )  & m1_subset_1(D, u1_struct_0(B)))  =>  (r2_hidden(A, a_3_3_lattice3(B, C, D)) <=>  (? [E] :  (m1_subset_1(E, u1_struct_0(B)) &  (A=k4_lattices(B, D, E) & r2_hidden(E, C)) ) ) ) ) ) ).
fof(involutiveness_k6_lattice3, axiom,  (! [A, B] :  ( (v1_partfun1(B, A) &  (v1_relat_2(B) &  (v4_relat_2(B) &  (v8_relat_2(B) & m1_subset_1(B, k1_zfmisc_1(k2_zfmisc_1(A, A)))) ) ) )  => k6_lattice3(A, k6_lattice3(A, B))=B) ) ).
fof(l26_lattice3, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v5_orders_2(A) &  (v1_lattice3(A) & l1_orders_2(A)) ) )  =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (D=k10_lattice3(A, B, C) <=>  (r1_orders_2(A, B, D) &  (r1_orders_2(A, C, D) &  (! [E] :  (m1_subset_1(E, u1_struct_0(A)) =>  ( (r1_orders_2(A, B, E) & r1_orders_2(A, C, E))  => r1_orders_2(A, D, E)) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(l28_lattice3, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v5_orders_2(A) &  (v2_lattice3(A) & l1_orders_2(A)) ) )  =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (D=k11_lattice3(A, B, C) <=>  (r1_orders_2(A, D, B) &  (r1_orders_2(A, D, C) &  (! [E] :  (m1_subset_1(E, u1_struct_0(A)) =>  ( (r1_orders_2(A, E, B) & r1_orders_2(A, E, C))  => r1_orders_2(A, E, D)) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(rc4_orders_2, axiom,  (? [A] :  (l1_orders_2(A) &  (v2_struct_0(A) & v1_orders_2(A)) ) ) ).
fof(redefinition_k12_lattice3, axiom,  (! [A, B, C] :  ( ( (v5_orders_2(A) &  (v2_lattice3(A) & l1_orders_2(A)) )  &  (m1_subset_1(B, u1_struct_0(A)) & m1_subset_1(C, u1_struct_0(A))) )  => k12_lattice3(A, B, C)=k11_lattice3(A, B, C)) ) ).
fof(redefinition_k13_lattice3, axiom,  (! [A, B, C] :  ( ( (v5_orders_2(A) &  (v1_lattice3(A) & l1_orders_2(A)) )  &  (m1_subset_1(B, u1_struct_0(A)) & m1_subset_1(C, u1_struct_0(A))) )  => k13_lattice3(A, B, C)=k10_lattice3(A, B, C)) ) ).
fof(redefinition_k2_lattice3, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v10_lattices(A) & l3_lattices(A)) )  => k2_lattice3(A)=k8_filter_1(A)) ) ).
fof(redefinition_k6_lattice3, axiom,  (! [A, B] :  ( (v1_partfun1(B, A) &  (v1_relat_2(B) &  (v4_relat_2(B) &  (v8_relat_2(B) & m1_subset_1(B, k1_zfmisc_1(k2_zfmisc_1(A, A)))) ) ) )  => k6_lattice3(A, B)=k4_relat_1(B)) ) ).
fof(s3_binop_1__e2_46__lattice3, axiom,  (! [A] :  ( (v3_orders_2(A) &  (v4_orders_2(A) &  (v5_orders_2(A) &  (v1_lattice3(A) &  (v2_lattice3(A) & l1_orders_2(A)) ) ) ) )  =>  ( (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (? [D] :  (m1_subset_1(D, u1_struct_0(A)) &  (! [E] :  (m1_subset_1(E, u1_struct_0(A)) =>  (! [F] :  (m1_subset_1(F, u1_struct_0(A)) =>  ( (E=B & F=C)  => D=k13_lattice3(A, E, F)) ) ) ) ) ) ) ) ) ) )  =>  (? [B] :  ( (v1_funct_1(B) &  (v1_funct_2(B, k2_zfmisc_1(u1_struct_0(A), u1_struct_0(A)), u1_struct_0(A)) & m1_subset_1(B, k1_zfmisc_1(k2_zfmisc_1(k2_zfmisc_1(u1_struct_0(A), u1_struct_0(A)), u1_struct_0(A))))) )  &  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (! [G] :  (m1_subset_1(G, u1_struct_0(A)) =>  (! [H] :  (m1_subset_1(H, u1_struct_0(A)) =>  ( (G=C & H=D)  => k2_binop_1(u1_struct_0(A), u1_struct_0(A), u1_struct_0(A), B, C, D)=k13_lattice3(A, G, H)) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(s3_binop_1__e5_46__lattice3, axiom,  (! [A] :  ( (v3_orders_2(A) &  (v4_orders_2(A) &  (v5_orders_2(A) &  (v1_lattice3(A) &  (v2_lattice3(A) & l1_orders_2(A)) ) ) ) )  =>  ( (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (? [D] :  (m1_subset_1(D, u1_struct_0(A)) &  (! [E] :  (m1_subset_1(E, u1_struct_0(A)) =>  (! [F] :  (m1_subset_1(F, u1_struct_0(A)) =>  ( (E=B & F=C)  => D=k12_lattice3(A, E, F)) ) ) ) ) ) ) ) ) ) )  =>  (? [B] :  ( (v1_funct_1(B) &  (v1_funct_2(B, k2_zfmisc_1(u1_struct_0(A), u1_struct_0(A)), u1_struct_0(A)) & m1_subset_1(B, k1_zfmisc_1(k2_zfmisc_1(k2_zfmisc_1(u1_struct_0(A), u1_struct_0(A)), u1_struct_0(A))))) )  &  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (! [G] :  (m1_subset_1(G, u1_struct_0(A)) =>  (! [H] :  (m1_subset_1(H, u1_struct_0(A)) =>  ( (G=C & H=D)  => k2_binop_1(u1_struct_0(A), u1_struct_0(A), u1_struct_0(A), B, C, D)=k12_lattice3(A, G, H)) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(t10_lattice3, axiom,  (! [A] :  (l1_orders_2(A) =>  (v1_lattice3(A) <=> v2_lattice3(k7_lattice3(A))) ) ) ).
fof(t11_lattice3, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v10_lattices(A) & l3_lattices(A)) )  =>  (v1_lattice3(k3_lattice3(A)) & v2_lattice3(k3_lattice3(A))) ) ) ).
fof(t12_lattice3, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l1_orders_2(A))  =>  (v3_lattice3(A) =>  (v1_lattice3(A) & v2_lattice3(A)) ) ) ) ).
fof(t13_lattice3, axiom,  (! [A] :  ( (v5_orders_2(A) &  (v1_lattice3(A) & l1_orders_2(A)) )  =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) => k10_lattice3(A, B, C)=k10_lattice3(A, C, B)) ) ) ) ) ) ).
fof(t14_lattice3, axiom,  (! [A] :  ( (v5_orders_2(A) &  (v1_lattice3(A) & l1_orders_2(A)) )  =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (v4_orders_2(A) => k10_lattice3(A, k10_lattice3(A, B, C), D)=k10_lattice3(A, B, k10_lattice3(A, C, D))) ) ) ) ) ) ) ) ) ).
fof(t15_lattice3, axiom,  (! [A] :  ( (v5_orders_2(A) &  (v2_lattice3(A) & l1_orders_2(A)) )  =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) => k11_lattice3(A, B, C)=k11_lattice3(A, C, B)) ) ) ) ) ) ).
fof(t16_lattice3, axiom,  (! [A] :  ( (v5_orders_2(A) &  (v2_lattice3(A) & l1_orders_2(A)) )  =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (v4_orders_2(A) => k11_lattice3(A, k11_lattice3(A, B, C), D)=k11_lattice3(A, B, k11_lattice3(A, C, D))) ) ) ) ) ) ) ) ) ).
fof(t17_lattice3, axiom,  (! [A] :  ( (v3_orders_2(A) &  (v5_orders_2(A) &  (v1_lattice3(A) &  (v2_lattice3(A) & l1_orders_2(A)) ) ) )  =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) => k13_lattice3(A, k12_lattice3(A, B, C), C)=C) ) ) ) ) ) ).
fof(t18_lattice3, axiom,  (! [A] :  ( (v3_orders_2(A) &  (v5_orders_2(A) &  (v1_lattice3(A) &  (v2_lattice3(A) & l1_orders_2(A)) ) ) )  =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) => k12_lattice3(A, B, k13_lattice3(A, B, C))=B) ) ) ) ) ) ).
fof(t19_lattice3, axiom,  (! [A] :  ( (v3_orders_2(A) &  (v4_orders_2(A) &  (v5_orders_2(A) &  (v1_lattice3(A) &  (v2_lattice3(A) & l1_orders_2(A)) ) ) ) )  =>  (? [B] :  ( ( ~ (v2_struct_0(B))  &  (v3_lattices(B) &  (v10_lattices(B) & l3_lattices(B)) ) )  & g1_orders_2(u1_struct_0(A), u1_orders_2(A))=k3_lattice3(B)) ) ) ) ).
fof(t1_lattice3, axiom,  (! [A] :  (! [B] :  (m1_subset_1(B, u1_struct_0(k1_lattice3(A))) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(k1_lattice3(A))) =>  (k1_lattices(k1_lattice3(A), B, C)=k2_xboole_0(B, C) & k2_lattices(k1_lattice3(A), B, C)=k3_xboole_0(B, C)) ) ) ) ) ) ).
fof(t20_lattice3, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v10_lattices(A) & l3_lattices(A)) )  =>  (k6_lattice3(u1_struct_0(A), k2_lattice3(A))=k2_lattice3(k1_lattice2(A)) & k7_lattice3(k3_lattice3(A))=k3_lattice3(k1_lattice2(A))) ) ) ).
fof(t21_lattice3, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v10_lattices(A) & l3_lattices(A)) )  =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (r3_lattice3(A, B, k7_domain_1(u1_struct_0(A), C, D)) <=> r3_lattices(A, B, k4_lattices(A, C, D))) ) ) ) ) ) ) ) ) ).
fof(t22_lattice3, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v10_lattices(A) & l3_lattices(A)) )  =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (r4_lattice3(A, B, k7_domain_1(u1_struct_0(A), C, D)) <=> r3_lattices(A, k3_lattices(A, C, D), B)) ) ) ) ) ) ) ) ) ).
fof(t23_lattice3, axiom,  (! [A] :  (! [B] :  ( ( ~ (v2_struct_0(B))  &  (v10_lattices(B) &  (v17_lattices(B) & l3_lattices(B)) ) )  =>  (! [C] :  (m1_subset_1(C, u1_struct_0(B)) =>  (r4_lattice3(B, C, A) <=> r3_lattice3(B, k7_lattices(B, C), a_2_0_lattice3(A, B))) ) ) ) ) ) ).
fof(t24_lattice3, axiom,  (! [A] :  (! [B] :  ( ( ~ (v2_struct_0(B))  &  (v10_lattices(B) &  (v17_lattices(B) & l3_lattices(B)) ) )  =>  (! [C] :  (m1_subset_1(C, u1_struct_0(B)) =>  (r3_lattice3(B, C, A) <=> r4_lattice3(B, k7_lattices(B, C), a_2_0_lattice3(A, B))) ) ) ) ) ) ).
fof(t25_lattice3, axiom,  (! [A] : v4_lattice3(k1_lattice3(A))) ).
fof(t26_lattice3, axiom,  (! [A] : v5_lattice3(k1_lattice3(A))) ).
fof(t27_lattice3, axiom,  (! [A] : v6_lattice3(k1_lattice3(A))) ).
fof(t28_lattice3, axiom,  (! [A] :  (! [B] :  ( ( ~ (v2_struct_0(B))  &  (v10_lattices(B) & l3_lattices(B)) )  =>  (! [C] :  (m1_subset_1(C, u1_struct_0(B)) =>  (r3_lattice3(B, C, A) <=> r1_lattice3(k3_lattice3(B), A, k4_lattice3(B, C))) ) ) ) ) ) ).
fof(t29_lattice3, axiom,  (! [A] :  (! [B] :  ( ( ~ (v2_struct_0(B))  &  (v10_lattices(B) & l3_lattices(B)) )  =>  (! [C] :  (m1_subset_1(C, u1_struct_0(k3_lattice3(B))) =>  (r1_lattice3(k3_lattice3(B), A, C) <=> r3_lattice3(B, k5_lattice3(B, C), A)) ) ) ) ) ) ).
fof(t2_binop_1, axiom,  (! [A] :  (! [B] :  (! [C] :  (! [D] :  ( (v1_funct_1(D) &  (v1_funct_2(D, k2_zfmisc_1(A, B), C) & m1_subset_1(D, k1_zfmisc_1(k2_zfmisc_1(k2_zfmisc_1(A, B), C)))) )  =>  (! [E] :  ( (v1_funct_1(E) &  (v1_funct_2(E, k2_zfmisc_1(A, B), C) & m1_subset_1(E, k1_zfmisc_1(k2_zfmisc_1(k2_zfmisc_1(A, B), C)))) )  =>  ( (! [F] :  (m1_subset_1(F, A) =>  (! [G] :  (m1_subset_1(G, B) => k1_binop_1(D, F, G)=k1_binop_1(E, F, G)) ) ) )  => r2_funct_2(k2_zfmisc_1(A, B), C, D, E)) ) ) ) ) ) ) ) ).
fof(t2_lattice3, axiom,  (! [A] :  (! [B] :  (m1_subset_1(B, u1_struct_0(k1_lattice3(A))) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(k1_lattice3(A))) =>  (r1_lattices(k1_lattice3(A), B, C) <=> r1_tarski(B, C)) ) ) ) ) ) ).
fof(t30_lattice3, axiom,  (! [A] :  (! [B] :  ( ( ~ (v2_struct_0(B))  &  (v10_lattices(B) & l3_lattices(B)) )  =>  (! [C] :  (m1_subset_1(C, u1_struct_0(B)) =>  (r4_lattice3(B, C, A) <=> r2_lattice3(k3_lattice3(B), A, k4_lattice3(B, C))) ) ) ) ) ) ).
fof(t31_lattice3, axiom,  (! [A] :  (! [B] :  ( ( ~ (v2_struct_0(B))  &  (v10_lattices(B) & l3_lattices(B)) )  =>  (! [C] :  (m1_subset_1(C, u1_struct_0(k3_lattice3(B))) =>  (r2_lattice3(k3_lattice3(B), A, C) <=> r4_lattice3(B, k5_lattice3(B, C), A)) ) ) ) ) ) ).
fof(t32_lattice3, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v10_lattices(A) &  (v4_lattice3(A) & l3_lattices(A)) ) )  =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] : r3_lattices(A, k15_lattice3(A, a_3_2_lattice3(A, B, C)), k4_lattices(A, B, k15_lattice3(A, C)))) ) ) ) ) ).
fof(t33_lattice3, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v10_lattices(A) &  (v4_lattice3(A) & l3_lattices(A)) ) )  =>  (v5_lattice3(A) <=>  (! [B] :  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) => r3_lattices(A, k4_lattices(A, C, k15_lattice3(A, B)), k15_lattice3(A, a_3_3_lattice3(A, B, C)))) ) ) ) ) ) ).
fof(t34_lattice3, conjecture,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v10_lattices(A) &  (v4_lattice3(A) & l3_lattices(A)) ) )  =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (B=k16_lattice3(A, C) <=>  (r3_lattice3(A, B, C) &  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (r3_lattice3(A, D, C) => r3_lattices(A, D, B)) ) ) ) ) ) ) ) ) ) ).
fof(t3_lattice3, axiom,  (! [A] :  (v13_lattices(k1_lattice3(A)) & k5_lattices(k1_lattice3(A))=k1_xboole_0) ) ).
fof(t4_lattice3, axiom,  (! [A] :  (v14_lattices(k1_lattice3(A)) & k6_lattices(k1_lattice3(A))=A) ) ).
fof(t53_lattice2, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v10_lattices(A) & l3_lattices(A)) )  =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (r3_lattices(A, B, C) =>  (! [D] :  (m1_subset_1(D, u1_struct_0(k1_lattice2(A))) =>  (! [E] :  (m1_subset_1(E, u1_struct_0(k1_lattice2(A))) =>  ( (B=D & C=E)  => r3_lattices(k1_lattice2(A), E, D)) ) ) ) ) ) ) ) ) ) ) ) ).
fof(t54_lattice2, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v10_lattices(A) & l3_lattices(A)) )  =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (! [D] :  (m1_subset_1(D, u1_struct_0(k1_lattice2(A))) =>  (! [E] :  (m1_subset_1(E, u1_struct_0(k1_lattice2(A))) =>  ( (r3_lattices(k1_lattice2(A), D, E) &  (B=D & C=E) )  => r3_lattices(A, C, B)) ) ) ) ) ) ) ) ) ) ) ).
fof(t5_lattice3, axiom,  (! [A] :  (! [B] :  (m1_subset_1(B, u1_struct_0(k1_lattice3(A))) => k7_lattices(k1_lattice3(A), B)=k6_subset_1(A, B)) ) ) ).
fof(t6_lattice3, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v10_lattices(A) & l3_lattices(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  &  (v10_lattices(B) & l3_lattices(B)) )  =>  (k3_lattice3(A)=k3_lattice3(B) => g3_lattices(u1_struct_0(A), u2_lattices(A), u1_lattices(A))=g3_lattices(u1_struct_0(B), u2_lattices(B), u1_lattices(B))) ) ) ) ) ).
fof(t7_filter_0, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v6_lattices(A) &  (v7_lattices(A) &  (v8_lattices(A) &  (v9_lattices(A) & l3_lattices(A)) ) ) ) )  =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  ( (r3_lattices(A, B, C) & r3_lattices(A, B, D))  => r3_lattices(A, B, k4_lattices(A, C, D))) ) ) ) ) ) ) ) ) ).
fof(t7_lattice3, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v10_lattices(A) & l3_lattices(A)) )  =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (r3_lattices(A, B, C) <=> r3_orders_2(k3_lattice3(A), k4_lattice3(A, B), k4_lattice3(A, C))) ) ) ) ) ) ) ).
fof(t8_lattice3, axiom,  (! [A] :  (l1_orders_2(A) => k7_lattice3(k7_lattice3(A))=g1_orders_2(u1_struct_0(A), u1_orders_2(A))) ) ).
fof(t9_lattice3, axiom,  (! [A] :  (l1_orders_2(A) =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (r1_orders_2(A, B, C) <=> r1_orders_2(k7_lattice3(A), k8_lattice3(A, C), k8_lattice3(A, B))) ) ) ) ) ) ) ).
