include('incl/xboole_0.ax').
include('incl/xboole_1.ax').
include('incl/enumset1.ax').
include('incl/zfmisc_1.ax').
include('incl/subset_1.ax').
include('incl/setfam_1.ax').
include('incl/relat_1.ax').
include('incl/funct_1.ax').
include('incl/ordinal1.ax').
include('incl/wellord1.ax').
include('incl/relset_1.ax').
include('incl/mcart_1.ax').
include('incl/wellord2.ax').
include('incl/funct_2.ax').
include('incl/finset_1.ax').
include('incl/pre_topc.ax').
include('incl/orders_2.ax').
include('incl/lattices.ax').
include('incl/tops_1.ax').
include('incl/tops_2.ax').
include('incl/compts_1.ax').
include('incl/connsp_2.ax').
include('incl/filter_1.ax').
include('incl/lattice3.ax').
include('incl/yellow_0.ax').
include('incl/yellow_1.ax').
include('incl/waybel_0.ax').
fof(commutativity_k1_tsep_1, axiom,  (! [A, B, C] :  ( ( ( ~ (v2_struct_0(A))  & l1_pre_topc(A))  &  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  &  ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A)) ) )  => k1_tsep_1(A, B, C)=k1_tsep_1(A, C, B)) ) ).
fof(d1_tmap_1, axiom,  (! [A] :  ( ~ (v1_xboole_0(A))  =>  (! [B] :  ( ~ (v1_xboole_0(B))  =>  (! [C] :  ( ( ~ (v1_xboole_0(C))  & m1_subset_1(C, k1_zfmisc_1(A)))  =>  (! [D] :  ( ( ~ (v1_xboole_0(D))  & m1_subset_1(D, k1_zfmisc_1(A)))  =>  (! [E] :  ( (v1_funct_1(E) &  (v1_funct_2(E, C, B) & m1_subset_1(E, k1_zfmisc_1(k2_zfmisc_1(C, B)))) )  =>  (! [F] :  ( (v1_funct_1(F) &  (v1_funct_2(F, D, B) & m1_subset_1(F, k1_zfmisc_1(k2_zfmisc_1(D, B)))) )  =>  (k2_partfun1(C, B, E, k9_subset_1(A, C, D))=k2_partfun1(D, B, F, k9_subset_1(A, C, D)) =>  (! [G] :  ( (v1_funct_1(G) &  (v1_funct_2(G, k4_subset_1(A, C, D), B) & m1_subset_1(G, k1_zfmisc_1(k2_zfmisc_1(k4_subset_1(A, C, D), B)))) )  =>  (G=k1_tmap_1(A, B, C, D, E, F) <=>  (k2_partfun1(k4_subset_1(A, C, D), B, G, C)=E & k2_partfun1(k4_subset_1(A, C, D), B, G, D)=F) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(d2_tsep_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l1_pre_topc(A))  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A))  =>  (! [D] :  ( ( ~ (v2_struct_0(D))  &  (v1_pre_topc(D) & m1_pre_topc(D, A)) )  =>  (D=k1_tsep_1(A, B, C) <=> u1_struct_0(D)=k2_xboole_0(u1_struct_0(B), u1_struct_0(C))) ) ) ) ) ) ) ) ) ).
fof(d3_tsep_1, axiom,  (! [A] :  (l1_struct_0(A) =>  (! [B] :  (l1_struct_0(B) =>  (r1_tsep_1(A, B) <=> r1_xboole_0(u1_struct_0(A), u1_struct_0(B))) ) ) ) ) ).
fof(d5_tsep_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l1_pre_topc(A))  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A))  =>  ( ~ (r1_tsep_1(B, C))  =>  (! [D] :  ( ( ~ (v2_struct_0(D))  &  (v1_pre_topc(D) & m1_pre_topc(D, A)) )  =>  (D=k2_tsep_1(A, B, C) <=> u1_struct_0(D)=k3_xboole_0(u1_struct_0(B), u1_struct_0(C))) ) ) ) ) ) ) ) ) ) ).
fof(dt_k1_tmap_1, axiom,  (! [A, B, C, D, E, F] :  ( ( ~ (v1_xboole_0(A))  &  ( ~ (v1_xboole_0(B))  &  ( ( ~ (v1_xboole_0(C))  & m1_subset_1(C, k1_zfmisc_1(A)))  &  ( ( ~ (v1_xboole_0(D))  & m1_subset_1(D, k1_zfmisc_1(A)))  &  ( (v1_funct_1(E) &  (v1_funct_2(E, C, B) & m1_subset_1(E, k1_zfmisc_1(k2_zfmisc_1(C, B)))) )  &  (v1_funct_1(F) &  (v1_funct_2(F, D, B) & m1_subset_1(F, k1_zfmisc_1(k2_zfmisc_1(D, B)))) ) ) ) ) ) )  =>  (v1_funct_1(k1_tmap_1(A, B, C, D, E, F)) &  (v1_funct_2(k1_tmap_1(A, B, C, D, E, F), k4_subset_1(A, C, D), B) & m1_subset_1(k1_tmap_1(A, B, C, D, E, F), k1_zfmisc_1(k2_zfmisc_1(k4_subset_1(A, C, D), B)))) ) ) ) ).
fof(dt_k1_tsep_1, axiom,  (! [A, B, C] :  ( ( ( ~ (v2_struct_0(A))  & l1_pre_topc(A))  &  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  &  ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A)) ) )  =>  ( ~ (v2_struct_0(k1_tsep_1(A, B, C)))  &  (v1_pre_topc(k1_tsep_1(A, B, C)) & m1_pre_topc(k1_tsep_1(A, B, C), A)) ) ) ) ).
fof(dt_k2_tsep_1, axiom,  (! [A, B, C] :  ( ( ( ~ (v2_struct_0(A))  & l1_pre_topc(A))  &  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  &  ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A)) ) )  =>  ( ~ (v2_struct_0(k2_tsep_1(A, B, C)))  &  (v1_pre_topc(k2_tsep_1(A, B, C)) & m1_pre_topc(k2_tsep_1(A, B, C), A)) ) ) ) ).
fof(fc1_tmap_1, axiom,  (! [A, B, C] :  ( ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  &  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  &  ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A)) ) )  =>  ( ~ (v2_struct_0(k1_tsep_1(A, B, C)))  &  (v1_pre_topc(k1_tsep_1(A, B, C)) & v2_pre_topc(k1_tsep_1(A, B, C))) ) ) ) ).
fof(irreflexivity_r2_subset_1, axiom,  (! [A, B] :  ( ( ~ (v1_xboole_0(A))  &  ~ (v1_xboole_0(B)) )  =>  ~ (r2_subset_1(A, A)) ) ) ).
fof(rc1_borsuk_1, axiom,  (! [A] :  ( (v2_pre_topc(A) & l1_pre_topc(A))  =>  (? [B] :  (m1_pre_topc(B, A) &  (v1_pre_topc(B) &  (v2_pre_topc(B) & v1_borsuk_1(B, A)) ) ) ) ) ) ).
fof(rc1_tsep_1, axiom,  (! [A] :  ( (v2_pre_topc(A) & l1_pre_topc(A))  =>  (? [B] :  (m1_pre_topc(B, A) &  (v1_pre_topc(B) &  (v2_pre_topc(B) & v1_tsep_1(B, A)) ) ) ) ) ) ).
fof(rc2_borsuk_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (? [B] :  (m1_pre_topc(B, A) &  ( ~ (v2_struct_0(B))  &  (v1_pre_topc(B) &  (v2_pre_topc(B) & v1_borsuk_1(B, A)) ) ) ) ) ) ) ).
fof(rc2_tsep_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (? [B] :  (m1_pre_topc(B, A) &  ( ~ (v2_struct_0(B))  &  (v1_pre_topc(B) &  (v2_pre_topc(B) & v1_tsep_1(B, A)) ) ) ) ) ) ) ).
fof(redefinition_r2_subset_1, axiom,  (! [A, B] :  ( ( ~ (v1_xboole_0(A))  &  ~ (v1_xboole_0(B)) )  =>  (r2_subset_1(A, B) <=> r1_xboole_0(A, B)) ) ) ).
fof(symmetry_r1_tsep_1, axiom,  (! [A, B] :  ( (l1_struct_0(A) & l1_struct_0(B))  =>  (r1_tsep_1(A, B) => r1_tsep_1(B, A)) ) ) ).
fof(symmetry_r2_subset_1, axiom,  (! [A, B] :  ( ( ~ (v1_xboole_0(A))  &  ~ (v1_xboole_0(B)) )  =>  (r2_subset_1(A, B) => r2_subset_1(B, A)) ) ) ).
fof(t10_tmap_1, axiom,  (! [A] :  ( ~ (v1_xboole_0(A))  =>  (! [B] :  ( ~ (v1_xboole_0(B))  =>  (! [C] :  ( ( ~ (v1_xboole_0(C))  & m1_subset_1(C, k1_zfmisc_1(A)))  =>  (! [D] :  ( ( ~ (v1_xboole_0(D))  & m1_subset_1(D, k1_zfmisc_1(A)))  =>  (! [E] :  ( (v1_funct_1(E) &  (v1_funct_2(E, C, B) & m1_subset_1(E, k1_zfmisc_1(k2_zfmisc_1(C, B)))) )  =>  (! [F] :  ( (v1_funct_1(F) &  (v1_funct_2(F, D, B) & m1_subset_1(F, k1_zfmisc_1(k2_zfmisc_1(D, B)))) )  =>  (k2_partfun1(C, B, E, k9_subset_1(A, C, D))=k2_partfun1(D, B, F, k9_subset_1(A, C, D)) =>  ( (m1_subset_1(C, k1_zfmisc_1(D)) => r1_funct_2(k4_subset_1(A, C, D), B, D, B, k1_tmap_1(A, B, C, D, E, F), F))  &  ( (r1_funct_2(k4_subset_1(A, C, D), B, D, B, k1_tmap_1(A, B, C, D, E, F), F) => m1_subset_1(C, k1_zfmisc_1(D)))  &  ( (m1_subset_1(D, k1_zfmisc_1(C)) => r1_funct_2(k4_subset_1(A, C, D), B, C, B, k1_tmap_1(A, B, C, D, E, F), E))  &  (r1_funct_2(k4_subset_1(A, C, D), B, C, B, k1_tmap_1(A, B, C, D, E, F), E) => m1_subset_1(D, k1_zfmisc_1(C))) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(t11_tmap_1, axiom,  (! [A] :  (l1_pre_topc(A) =>  (! [B] :  (m1_pre_topc(B, A) =>  (v1_pre_topc(g1_pre_topc(u1_struct_0(B), u1_pre_topc(B))) & m1_pre_topc(g1_pre_topc(u1_struct_0(B), u1_pre_topc(B)), A)) ) ) ) ) ).
fof(t11_tsep_1, axiom,  (! [A] :  ( (v2_pre_topc(A) & l1_pre_topc(A))  =>  (! [B] :  (m1_pre_topc(B, A) =>  (! [C] :  (m1_subset_1(C, k1_zfmisc_1(u1_struct_0(A))) =>  (C=u1_struct_0(B) =>  ( (v1_borsuk_1(B, A) & m1_pre_topc(B, A))  <=> v4_pre_topc(C, A)) ) ) ) ) ) ) ) ).
fof(t12_tmap_1, axiom,  (! [A] :  (l1_pre_topc(A) =>  (! [B] :  ( (v2_pre_topc(B) & l1_pre_topc(B))  =>  (! [C] :  ( (v2_pre_topc(C) & l1_pre_topc(C))  =>  (B=g1_pre_topc(u1_struct_0(C), u1_pre_topc(C)) =>  (m1_pre_topc(B, A) <=> m1_pre_topc(C, A)) ) ) ) ) ) ) ) ).
fof(t13_tmap_1, axiom,  (! [A] :  ( (v2_pre_topc(A) & l1_pre_topc(A))  =>  (! [B] :  ( (v2_pre_topc(B) & l1_pre_topc(B))  =>  (! [C] :  ( (v2_pre_topc(C) & l1_pre_topc(C))  =>  (C=g1_pre_topc(u1_struct_0(B), u1_pre_topc(B)) =>  ( (v1_borsuk_1(B, A) & m1_pre_topc(B, A))  <=>  (v1_borsuk_1(C, A) & m1_pre_topc(C, A)) ) ) ) ) ) ) ) ) ).
fof(t14_tmap_1, axiom,  (! [A] :  ( (v2_pre_topc(A) & l1_pre_topc(A))  =>  (! [B] :  ( (v2_pre_topc(B) & l1_pre_topc(B))  =>  (! [C] :  ( (v2_pre_topc(C) & l1_pre_topc(C))  =>  (C=g1_pre_topc(u1_struct_0(B), u1_pre_topc(B)) =>  ( (v1_tsep_1(B, A) & m1_pre_topc(B, A))  <=>  (v1_tsep_1(C, A) & m1_pre_topc(C, A)) ) ) ) ) ) ) ) ) ).
fof(t15_tmap_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A))  =>  (m1_pre_topc(B, C) =>  (! [D] :  (m1_subset_1(D, u1_struct_0(B)) =>  (? [E] :  (m1_subset_1(E, u1_struct_0(C)) & E=D) ) ) ) ) ) ) ) ) ) ) ).
fof(t16_tmap_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A))  =>  (! [D] :  (m1_subset_1(D, u1_struct_0(k1_tsep_1(A, B, C))) =>  ~ ( ( (! [E] :  (m1_subset_1(E, u1_struct_0(B)) =>  ~ (E=D) ) )  &  (! [E] :  (m1_subset_1(E, u1_struct_0(C)) =>  ~ (E=D) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(t16_tsep_1, axiom,  (! [A] :  ( (v2_pre_topc(A) & l1_pre_topc(A))  =>  (! [B] :  (m1_pre_topc(B, A) =>  (! [C] :  (m1_subset_1(C, k1_zfmisc_1(u1_struct_0(A))) =>  (C=u1_struct_0(B) =>  ( (v1_tsep_1(B, A) & m1_pre_topc(B, A))  <=> v3_pre_topc(C, A)) ) ) ) ) ) ) ) ).
fof(t17_tmap_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A))  =>  ( ~ (r1_tsep_1(B, C))  =>  (! [D] :  (m1_subset_1(D, u1_struct_0(k2_tsep_1(A, B, C))) =>  ( (? [E] :  (m1_subset_1(E, u1_struct_0(B)) & E=D) )  &  (? [E] :  (m1_subset_1(E, u1_struct_0(C)) & E=D) ) ) ) ) ) ) ) ) ) ) ) ).
fof(t18_tmap_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A))  =>  (! [D] :  (m1_subset_1(D, u1_struct_0(k1_tsep_1(A, B, C))) =>  (! [E] :  (m1_subset_1(E, k1_zfmisc_1(u1_struct_0(B))) =>  (! [F] :  (m1_subset_1(F, k1_zfmisc_1(u1_struct_0(C))) =>  ~ ( (v4_pre_topc(E, B) &  (r2_hidden(D, E) &  (v4_pre_topc(F, C) &  (r2_hidden(D, F) &  (! [G] :  (m1_subset_1(G, k1_zfmisc_1(u1_struct_0(k1_tsep_1(A, B, C)))) =>  ~ ( (v4_pre_topc(G, k1_tsep_1(A, B, C)) &  (r2_hidden(D, G) & r1_tarski(G, k2_xboole_0(E, F))) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(t19_tmap_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A))  =>  (! [D] :  (m1_subset_1(D, u1_struct_0(k1_tsep_1(A, B, C))) =>  (! [E] :  (m1_subset_1(E, k1_zfmisc_1(u1_struct_0(B))) =>  (! [F] :  (m1_subset_1(F, k1_zfmisc_1(u1_struct_0(C))) =>  ~ ( (v3_pre_topc(E, B) &  (r2_hidden(D, E) &  (v3_pre_topc(F, C) &  (r2_hidden(D, F) &  (! [G] :  (m1_subset_1(G, k1_zfmisc_1(u1_struct_0(k1_tsep_1(A, B, C)))) =>  ~ ( (v3_pre_topc(G, k1_tsep_1(A, B, C)) &  (r2_hidden(D, G) & r1_tarski(G, k2_xboole_0(E, F))) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(t1_tsep_1, axiom,  (! [A] :  (l1_pre_topc(A) =>  (! [B] :  (m1_pre_topc(B, A) => m1_subset_1(u1_struct_0(B), k1_zfmisc_1(u1_struct_0(A)))) ) ) ) ).
fof(t20_tmap_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A))  =>  (! [D] :  (m1_subset_1(D, u1_struct_0(k1_tsep_1(A, B, C))) =>  (! [E] :  (m1_subset_1(E, u1_struct_0(B)) =>  (! [F] :  (m1_subset_1(F, u1_struct_0(C)) =>  ( (E=D & F=D)  =>  (! [G] :  (m1_connsp_2(G, B, E) =>  (! [H] :  (m1_connsp_2(H, C, F) =>  (? [I] :  (m1_subset_1(I, k1_zfmisc_1(u1_struct_0(k1_tsep_1(A, B, C)))) &  (v3_pre_topc(I, k1_tsep_1(A, B, C)) &  (r2_hidden(D, I) & r1_tarski(I, k2_xboole_0(G, H))) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(t21_tmap_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A))  =>  (! [D] :  (m1_subset_1(D, u1_struct_0(k1_tsep_1(A, B, C))) =>  (! [E] :  (m1_subset_1(E, u1_struct_0(B)) =>  (! [F] :  (m1_subset_1(F, u1_struct_0(C)) =>  ( (E=D & F=D)  =>  (! [G] :  (m1_connsp_2(G, B, E) =>  (! [H] :  (m1_connsp_2(H, C, F) =>  (? [I] :  (m1_connsp_2(I, k1_tsep_1(A, B, C), D) & r1_tarski(I, k2_xboole_0(G, H))) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(t22_tmap_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A))  =>  (m1_pre_topc(B, C) =>  ( ~ (r1_tsep_1(B, C))  &  ~ (r1_tsep_1(C, B)) ) ) ) ) ) ) ) ) ).
fof(t22_tsep_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A))  => m1_pre_topc(B, k1_tsep_1(A, B, C))) ) ) ) ) ) ).
fof(t23_tmap_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A))  =>  (! [D] :  ( ( ~ (v2_struct_0(D))  & m1_pre_topc(D, A))  =>  (m1_pre_topc(B, C) =>  ( (r1_tsep_1(B, D) & r1_tsep_1(D, B))  |  ( ~ (r1_tsep_1(C, D))  &  ~ (r1_tsep_1(D, C)) ) ) ) ) ) ) ) ) ) ) ) ).
fof(t23_tsep_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A))  =>  (m1_pre_topc(B, C) <=> k1_tsep_1(A, B, C)=g1_pre_topc(u1_struct_0(C), u1_pre_topc(C))) ) ) ) ) ) ) ).
fof(t24_tmap_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A))  =>  (! [D] :  ( ( ~ (v2_struct_0(D))  & m1_pre_topc(D, A))  =>  (m1_pre_topc(B, C) =>  ( ( ~ (r1_tsep_1(C, D))  &  ~ (r1_tsep_1(D, C)) )  |  (r1_tsep_1(B, D) & r1_tsep_1(D, B)) ) ) ) ) ) ) ) ) ) ) ).
fof(t25_tmap_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  => k1_tsep_1(A, B, B)=g1_pre_topc(u1_struct_0(B), u1_pre_topc(B))) ) ) ) ).
fof(t26_tmap_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  => k2_tsep_1(A, B, B)=g1_pre_topc(u1_struct_0(B), u1_pre_topc(B))) ) ) ) ).
fof(t27_tmap_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A))  =>  (! [D] :  ( ( ~ (v2_struct_0(D))  & m1_pre_topc(D, A))  =>  (! [E] :  ( ( ~ (v2_struct_0(E))  & m1_pre_topc(E, A))  =>  ( (m1_pre_topc(B, C) & m1_pre_topc(D, E))  => m1_pre_topc(k1_tsep_1(A, B, D), k1_tsep_1(A, C, E))) ) ) ) ) ) ) ) ) ) ) ).
fof(t28_tmap_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A))  =>  (! [D] :  ( ( ~ (v2_struct_0(D))  & m1_pre_topc(D, A))  =>  (! [E] :  ( ( ~ (v2_struct_0(E))  & m1_pre_topc(E, A))  =>  ( (m1_pre_topc(B, D) & m1_pre_topc(C, E))  =>  (r1_tsep_1(B, C) | m1_pre_topc(k2_tsep_1(A, B, C), k2_tsep_1(A, D, E))) ) ) ) ) ) ) ) ) ) ) ) ).
fof(t29_tmap_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A))  =>  (! [D] :  ( ( ~ (v2_struct_0(D))  & m1_pre_topc(D, A))  =>  ( (m1_pre_topc(B, C) & m1_pre_topc(D, C))  => m1_pre_topc(k1_tsep_1(A, B, D), C)) ) ) ) ) ) ) ) ) ).
fof(t29_tsep_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A))  =>  (! [D] :  ( ( ~ (v2_struct_0(D))  & m1_pre_topc(D, A))  =>  ( ( ~ (r1_tsep_1(B, C))  => k2_tsep_1(A, B, C)=k2_tsep_1(A, C, B))  &  ( ( ( ~ (r1_tsep_1(B, C))  &  ~ (r1_tsep_1(k2_tsep_1(A, B, C), D)) )  |  ( ~ (r1_tsep_1(C, D))  &  ~ (r1_tsep_1(B, k2_tsep_1(A, C, D))) ) )  => k2_tsep_1(A, k2_tsep_1(A, B, C), D)=k2_tsep_1(A, B, k2_tsep_1(A, C, D))) ) ) ) ) ) ) ) ) ) ).
fof(t2_tsep_1, axiom,  (! [A] :  (l1_pre_topc(A) => m1_pre_topc(A, A)) ) ).
fof(t30_tmap_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A))  =>  (! [D] :  ( ( ~ (v2_struct_0(D))  & m1_pre_topc(D, A))  =>  ( (m1_pre_topc(B, D) & m1_pre_topc(C, D))  =>  (r1_tsep_1(B, C) | m1_pre_topc(k2_tsep_1(A, B, C), D)) ) ) ) ) ) ) ) ) ) ).
fof(t30_tsep_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A))  =>  ( ~ (r1_tsep_1(B, C))  =>  (m1_pre_topc(k2_tsep_1(A, B, C), B) & m1_pre_topc(k2_tsep_1(A, B, C), C)) ) ) ) ) ) ) ) ).
fof(t31_tmap_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A))  =>  (! [D] :  ( ( ~ (v2_struct_0(D))  & m1_pre_topc(D, A))  =>  ( ~ ( ( (r1_tsep_1(B, C) | r1_tsep_1(C, B))  &  ( ~ ( (r1_tsep_1(D, C) & r1_tsep_1(C, D)) )  &  ~ ( (k2_tsep_1(A, k1_tsep_1(A, B, D), C)=k2_tsep_1(A, D, C) & k2_tsep_1(A, C, k1_tsep_1(A, B, D))=k2_tsep_1(A, C, D)) ) ) ) )  &  ~ ( ( ~ ( (r1_tsep_1(B, C) & r1_tsep_1(C, B)) )  &  ( (r1_tsep_1(D, C) | r1_tsep_1(C, D))  &  ~ ( (k2_tsep_1(A, k1_tsep_1(A, B, D), C)=k2_tsep_1(A, B, C) & k2_tsep_1(A, C, k1_tsep_1(A, B, D))=k2_tsep_1(A, C, B)) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(t31_tsep_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A))  =>  ( ~ (r1_tsep_1(B, C))  =>  ( (m1_pre_topc(B, C) => k2_tsep_1(A, B, C)=g1_pre_topc(u1_struct_0(B), u1_pre_topc(B)))  &  ( (k2_tsep_1(A, B, C)=g1_pre_topc(u1_struct_0(B), u1_pre_topc(B)) => m1_pre_topc(B, C))  &  ( (m1_pre_topc(C, B) => k2_tsep_1(A, B, C)=g1_pre_topc(u1_struct_0(C), u1_pre_topc(C)))  &  (k2_tsep_1(A, B, C)=g1_pre_topc(u1_struct_0(C), u1_pre_topc(C)) => m1_pre_topc(C, B)) ) ) ) ) ) ) ) ) ) ) ).
fof(t32_tmap_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A))  =>  (! [D] :  ( ( ~ (v2_struct_0(D))  & m1_pre_topc(D, A))  =>  ( ~ (r1_tsep_1(B, C))  =>  ( (m1_pre_topc(B, D) => m1_pre_topc(k2_tsep_1(A, B, C), k2_tsep_1(A, D, C)))  &  (m1_pre_topc(C, D) => m1_pre_topc(k2_tsep_1(A, B, C), k2_tsep_1(A, B, D))) ) ) ) ) ) ) ) ) ) ) ).
fof(t33_tmap_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A))  =>  (! [D] :  ( ( ~ (v2_struct_0(D))  & m1_pre_topc(D, A))  =>  (m1_pre_topc(B, C) =>  ( ( ~ (r1_tsep_1(C, D))  &  ~ (r1_tsep_1(D, C)) )  |  (k2_tsep_1(A, C, k1_tsep_1(A, B, D))=g1_pre_topc(u1_struct_0(B), u1_pre_topc(B)) & k2_tsep_1(A, C, k1_tsep_1(A, D, B))=g1_pre_topc(u1_struct_0(B), u1_pre_topc(B))) ) ) ) ) ) ) ) ) ) ) ).
fof(t34_tmap_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A))  =>  (! [D] :  ( ( ~ (v2_struct_0(D))  & m1_pre_topc(D, A))  =>  ( ~ (r1_tsep_1(B, C))  =>  ( (m1_pre_topc(B, D) =>  ( ~ (r1_tsep_1(k2_tsep_1(A, D, C), B))  &  ~ (r1_tsep_1(k2_tsep_1(A, C, D), B)) ) )  &  (m1_pre_topc(C, D) =>  ( ~ (r1_tsep_1(k2_tsep_1(A, B, D), C))  &  ~ (r1_tsep_1(k2_tsep_1(A, D, B), C)) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(t35_tmap_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A))  =>  (! [D] :  ( ( ~ (v2_struct_0(D))  & m1_pre_topc(D, A))  =>  (! [E] :  ( ( ~ (v2_struct_0(E))  & m1_pre_topc(E, A))  =>  ( (m1_pre_topc(B, C) & m1_pre_topc(D, E))  =>  ( ( ~ (r1_tsep_1(C, E))  &  ~ (r1_tsep_1(k2_tsep_1(A, C, E), k1_tsep_1(A, B, D))) )  |  (r1_tsep_1(C, D) & r1_tsep_1(E, B)) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(t36_tmap_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A))  =>  (! [D] :  ( ( ~ (v2_struct_0(D))  & m1_pre_topc(D, A))  =>  (! [E] :  ( ( ~ (v2_struct_0(E))  & m1_pre_topc(E, A))  =>  ( (m1_pre_topc(k1_tsep_1(A, B, C), k1_tsep_1(A, D, E)) &  (m1_pre_topc(k2_tsep_1(A, D, k1_tsep_1(A, B, C)), B) & m1_pre_topc(k2_tsep_1(A, E, k1_tsep_1(A, B, C)), C)) )  =>  (m1_pre_topc(B, C) |  (m1_pre_topc(C, B) |  ( ~ (r1_tsep_1(D, k1_tsep_1(A, B, C)))  &  ~ (r1_tsep_1(E, k1_tsep_1(A, B, C))) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(t37_tmap_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A))  =>  (! [D] :  ( ( ~ (v2_struct_0(D))  & m1_pre_topc(D, A))  =>  (! [E] :  ( ( ~ (v2_struct_0(E))  & m1_pre_topc(E, A))  =>  (! [F] :  ( ( ~ (v2_struct_0(F))  & m1_pre_topc(F, A))  =>  ( (g1_pre_topc(u1_struct_0(A), u1_pre_topc(A))=k1_tsep_1(A, k1_tsep_1(A, D, E), F) &  (m1_pre_topc(k2_tsep_1(A, D, k1_tsep_1(A, B, C)), B) &  (m1_pre_topc(k2_tsep_1(A, E, k1_tsep_1(A, B, C)), C) & m1_pre_topc(k2_tsep_1(A, F, k1_tsep_1(A, B, C)), k2_tsep_1(A, B, C))) ) )  =>  (r1_tsep_1(B, C) |  (m1_pre_topc(B, C) |  (m1_pre_topc(C, B) |  ( ~ (r1_tsep_1(D, k1_tsep_1(A, B, C)))  &  ~ (r1_tsep_1(E, k1_tsep_1(A, B, C))) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(t38_tmap_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A))  =>  (! [D] :  ( ( ~ (v2_struct_0(D))  & m1_pre_topc(D, A))  =>  (! [E] :  ( ( ~ (v2_struct_0(E))  & m1_pre_topc(E, A))  =>  (! [F] :  ( ( ~ (v2_struct_0(F))  & m1_pre_topc(F, A))  =>  ( (g1_pre_topc(u1_struct_0(A), u1_pre_topc(A))=k1_tsep_1(A, k1_tsep_1(A, D, E), F) &  (m1_pre_topc(k2_tsep_1(A, D, k1_tsep_1(A, B, C)), B) &  (m1_pre_topc(k2_tsep_1(A, E, k1_tsep_1(A, B, C)), C) & m1_pre_topc(k2_tsep_1(A, F, k1_tsep_1(A, B, C)), k2_tsep_1(A, B, C))) ) )  =>  (r1_tsep_1(B, C) |  (m1_pre_topc(B, C) |  (m1_pre_topc(C, B) |  (m1_pre_topc(k1_tsep_1(A, B, C), k1_tsep_1(A, D, E)) |  ( ~ (r1_tsep_1(k1_tsep_1(A, D, E), k1_tsep_1(A, B, C)))  &  ~ (r1_tsep_1(F, k1_tsep_1(A, B, C))) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(t39_tmap_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A))  =>  (! [D] :  ( ( ~ (v2_struct_0(D))  & m1_pre_topc(D, A))  =>  ( ~ ( ( ~ (r1_tsep_1(k1_tsep_1(A, B, C), D))  &  (r1_tsep_1(B, D) & r1_tsep_1(C, D)) ) )  &  ( ~ ( ( ~ ( (r1_tsep_1(B, D) & r1_tsep_1(C, D)) )  & r1_tsep_1(k1_tsep_1(A, B, C), D)) )  &  ( ~ ( ( ~ (r1_tsep_1(D, k1_tsep_1(A, B, C)))  &  (r1_tsep_1(D, B) & r1_tsep_1(D, C)) ) )  &  ~ ( ( ~ ( (r1_tsep_1(D, B) & r1_tsep_1(D, C)) )  & r1_tsep_1(D, k1_tsep_1(A, B, C))) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(t40_tmap_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A))  =>  (! [D] :  ( ( ~ (v2_struct_0(D))  & m1_pre_topc(D, A))  =>  ( (r1_tsep_1(k1_tsep_1(A, B, C), D) =>  (r1_tsep_1(B, D) & r1_tsep_1(C, D)) )  &  ( ( (r1_tsep_1(B, D) & r1_tsep_1(C, D))  => r1_tsep_1(k1_tsep_1(A, B, C), D))  &  ( (r1_tsep_1(D, k1_tsep_1(A, B, C)) =>  (r1_tsep_1(D, B) & r1_tsep_1(D, C)) )  &  ( (r1_tsep_1(D, B) & r1_tsep_1(D, C))  => r1_tsep_1(D, k1_tsep_1(A, B, C))) ) ) ) ) ) ) ) ) ) ) ) ).
fof(t41_tmap_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A))  =>  (! [D] :  ( ( ~ (v2_struct_0(D))  & m1_pre_topc(D, A))  =>  ( ~ (r1_tsep_1(B, C))  =>  ( ( ~ (r1_tsep_1(k2_tsep_1(A, B, C), D))  =>  ( ~ (r1_tsep_1(B, D))  &  ~ (r1_tsep_1(C, D)) ) )  &  ( ~ (r1_tsep_1(D, k2_tsep_1(A, B, C)))  =>  ( ~ (r1_tsep_1(D, B))  &  ~ (r1_tsep_1(D, C)) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(t42_tmap_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A))  =>  (! [D] :  ( ( ~ (v2_struct_0(D))  & m1_pre_topc(D, A))  =>  ( ~ (r1_tsep_1(B, C))  =>  ( ( (r1_tsep_1(B, D) | r1_tsep_1(C, D))  => r1_tsep_1(k2_tsep_1(A, B, C), D))  &  ( (r1_tsep_1(D, B) | r1_tsep_1(D, C))  => r1_tsep_1(D, k2_tsep_1(A, B, C))) ) ) ) ) ) ) ) ) ) ) ).
fof(t43_tmap_1, conjecture,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  &  (v1_borsuk_1(C, A) & m1_pre_topc(C, A)) )  =>  ( ~ (r1_tsep_1(C, B))  =>  (v1_borsuk_1(k2_tsep_1(A, C, B), B) & m1_pre_topc(k2_tsep_1(A, C, B), B)) ) ) ) ) ) ) ) ).
fof(t4_tsep_1, axiom,  (! [A] :  ( (v2_pre_topc(A) & l1_pre_topc(A))  =>  (! [B] :  (m1_pre_topc(B, A) =>  (! [C] :  (m1_pre_topc(C, A) =>  (r1_tarski(u1_struct_0(B), u1_struct_0(C)) <=> m1_pre_topc(B, C)) ) ) ) ) ) ) ).
fof(t5_tsep_1, axiom,  (! [A] :  (l1_pre_topc(A) =>  (! [B] :  (m1_pre_topc(B, A) =>  (! [C] :  (m1_pre_topc(C, A) =>  (u1_struct_0(B)=u1_struct_0(C) => g1_pre_topc(u1_struct_0(B), u1_pre_topc(B))=g1_pre_topc(u1_struct_0(C), u1_pre_topc(C))) ) ) ) ) ) ) ).
fof(t6_tmap_1, axiom,  (! [A] :  ( ~ (v1_xboole_0(A))  =>  (! [B] :  ( ~ (v1_xboole_0(B))  =>  (! [C] :  ( ( ~ (v1_xboole_0(C))  & m1_subset_1(C, k1_zfmisc_1(A)))  =>  (! [D] :  ( ( ~ (v1_xboole_0(D))  & m1_subset_1(D, k1_zfmisc_1(A)))  =>  (r1_subset_1(C, D) =>  (! [E] :  ( (v1_funct_1(E) &  (v1_funct_2(E, C, B) & m1_subset_1(E, k1_zfmisc_1(k2_zfmisc_1(C, B)))) )  =>  (! [F] :  ( (v1_funct_1(F) &  (v1_funct_2(F, D, B) & m1_subset_1(F, k1_zfmisc_1(k2_zfmisc_1(D, B)))) )  =>  (k2_partfun1(C, B, E, k9_subset_1(A, C, D))=k2_partfun1(D, B, F, k9_subset_1(A, C, D)) &  (k2_partfun1(k4_subset_1(A, C, D), B, k1_tmap_1(A, B, C, D, E, F), C)=E & k2_partfun1(k4_subset_1(A, C, D), B, k1_tmap_1(A, B, C, D, E, F), D)=F) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(t7_tmap_1, axiom,  (! [A] :  ( ~ (v1_xboole_0(A))  =>  (! [B] :  ( ~ (v1_xboole_0(B))  =>  (! [C] :  ( ( ~ (v1_xboole_0(C))  & m1_subset_1(C, k1_zfmisc_1(A)))  =>  (! [D] :  ( ( ~ (v1_xboole_0(D))  & m1_subset_1(D, k1_zfmisc_1(A)))  =>  (! [E] :  ( (v1_funct_1(E) &  (v1_funct_2(E, k4_subset_1(A, C, D), B) & m1_subset_1(E, k1_zfmisc_1(k2_zfmisc_1(k4_subset_1(A, C, D), B)))) )  =>  (! [F] :  ( (v1_funct_1(F) &  (v1_funct_2(F, C, B) & m1_subset_1(F, k1_zfmisc_1(k2_zfmisc_1(C, B)))) )  =>  (! [G] :  ( (v1_funct_1(G) &  (v1_funct_2(G, D, B) & m1_subset_1(G, k1_zfmisc_1(k2_zfmisc_1(D, B)))) )  =>  ( (k2_partfun1(k4_subset_1(A, C, D), B, E, C)=F & k2_partfun1(k4_subset_1(A, C, D), B, E, D)=G)  => r2_funct_2(k4_subset_1(A, C, D), B, E, k1_tmap_1(A, B, C, D, F, G))) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(t8_tmap_1, axiom,  (! [A] :  ( ~ (v1_xboole_0(A))  =>  (! [B] :  ( ~ (v1_xboole_0(B))  =>  (! [C] :  ( ( ~ (v1_xboole_0(C))  & m1_subset_1(C, k1_zfmisc_1(A)))  =>  (! [D] :  ( ( ~ (v1_xboole_0(D))  & m1_subset_1(D, k1_zfmisc_1(A)))  =>  (! [E] :  ( (v1_funct_1(E) &  (v1_funct_2(E, C, B) & m1_subset_1(E, k1_zfmisc_1(k2_zfmisc_1(C, B)))) )  =>  (! [F] :  ( (v1_funct_1(F) &  (v1_funct_2(F, D, B) & m1_subset_1(F, k1_zfmisc_1(k2_zfmisc_1(D, B)))) )  =>  (k2_partfun1(C, B, E, k9_subset_1(A, C, D))=k2_partfun1(D, B, F, k9_subset_1(A, C, D)) => r1_funct_2(k4_subset_1(A, C, D), B, k4_subset_1(A, D, C), B, k1_tmap_1(A, B, C, D, E, F), k1_tmap_1(A, B, D, C, F, E))) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(t9_tmap_1, axiom,  (! [A] :  ( ~ (v1_xboole_0(A))  =>  (! [B] :  ( ~ (v1_xboole_0(B))  =>  (! [C] :  ( ( ~ (v1_xboole_0(C))  & m1_subset_1(C, k1_zfmisc_1(A)))  =>  (! [D] :  ( ( ~ (v1_xboole_0(D))  & m1_subset_1(D, k1_zfmisc_1(A)))  =>  (! [E] :  ( ( ~ (v1_xboole_0(E))  & m1_subset_1(E, k1_zfmisc_1(A)))  =>  (! [F] :  ( ( ~ (v1_xboole_0(F))  & m1_subset_1(F, k1_zfmisc_1(A)))  =>  (! [G] :  ( ( ~ (v1_xboole_0(G))  & m1_subset_1(G, k1_zfmisc_1(A)))  =>  ( (F=k4_subset_1(A, C, D) & G=k4_subset_1(A, D, E))  =>  (! [H] :  ( (v1_funct_1(H) &  (v1_funct_2(H, C, B) & m1_subset_1(H, k1_zfmisc_1(k2_zfmisc_1(C, B)))) )  =>  (! [I] :  ( (v1_funct_1(I) &  (v1_funct_2(I, D, B) & m1_subset_1(I, k1_zfmisc_1(k2_zfmisc_1(D, B)))) )  =>  (! [J] :  ( (v1_funct_1(J) &  (v1_funct_2(J, E, B) & m1_subset_1(J, k1_zfmisc_1(k2_zfmisc_1(E, B)))) )  =>  ( (k2_partfun1(C, B, H, k9_subset_1(A, C, D))=k2_partfun1(D, B, I, k9_subset_1(A, C, D)) &  (k2_partfun1(D, B, I, k9_subset_1(A, D, E))=k2_partfun1(E, B, J, k9_subset_1(A, D, E)) & k2_partfun1(C, B, H, k9_subset_1(A, C, E))=k2_partfun1(E, B, J, k9_subset_1(A, C, E))) )  =>  (! [K] :  ( (v1_funct_1(K) &  (v1_funct_2(K, F, B) & m1_subset_1(K, k1_zfmisc_1(k2_zfmisc_1(F, B)))) )  =>  (! [L] :  ( (v1_funct_1(L) &  (v1_funct_2(L, G, B) & m1_subset_1(L, k1_zfmisc_1(k2_zfmisc_1(G, B)))) )  =>  ( (r1_funct_2(F, B, k4_subset_1(A, C, D), B, K, k1_tmap_1(A, B, C, D, H, I)) & r1_funct_2(G, B, k4_subset_1(A, D, E), B, L, k1_tmap_1(A, B, D, E, I, J)))  => r1_funct_2(k4_subset_1(A, F, E), B, k4_subset_1(A, C, G), B, k1_tmap_1(A, B, F, E, K, J), k1_tmap_1(A, B, C, G, H, L))) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
