include('incl/xboole_0.ax').
include('incl/xboole_1.ax').
include('incl/enumset1.ax').
include('incl/zfmisc_1.ax').
include('incl/subset_1.ax').
include('incl/setfam_1.ax').
include('incl/relat_1.ax').
include('incl/funct_1.ax').
include('incl/ordinal1.ax').
include('incl/wellord1.ax').
include('incl/relset_1.ax').
include('incl/mcart_1.ax').
include('incl/wellord2.ax').
include('incl/funct_2.ax').
include('incl/finset_1.ax').
include('incl/pre_topc.ax').
include('incl/orders_2.ax').
include('incl/lattices.ax').
include('incl/tops_1.ax').
include('incl/tops_2.ax').
include('incl/compts_1.ax').
include('incl/connsp_2.ax').
include('incl/filter_1.ax').
include('incl/lattice3.ax').
fof(cc1_yellow_0, axiom,  (! [A] :  (l1_orders_2(A) =>  ( ( ~ (v2_struct_0(A))  & v3_lattice3(A))  =>  ( ~ (v2_struct_0(A))  &  (v1_lattice3(A) & v2_lattice3(A)) ) ) ) ) ).
fof(cc2_yellow_0, axiom,  (! [A] :  (l1_orders_2(A) =>  ( ( ~ (v2_struct_0(A))  &  (v7_struct_0(A) & v3_orders_2(A)) )  =>  ( ~ (v2_struct_0(A))  &  (v3_orders_2(A) &  (v4_orders_2(A) &  (v5_orders_2(A) & v3_lattice3(A)) ) ) ) ) ) ) ).
fof(cc3_yellow_0, axiom,  (! [A] :  (l1_orders_2(A) =>  ( ( ~ (v2_struct_0(A))  & v3_lattice3(A))  =>  ( ~ (v2_struct_0(A))  & v3_yellow_0(A)) ) ) ) ).
fof(cc4_yellow_0, axiom,  (! [A] :  (l1_orders_2(A) =>  (v3_yellow_0(A) =>  (v1_yellow_0(A) & v2_yellow_0(A)) ) ) ) ).
fof(cc5_yellow_0, axiom,  (! [A] :  (l1_orders_2(A) =>  ( (v1_yellow_0(A) & v2_yellow_0(A))  => v3_yellow_0(A)) ) ) ).
fof(d10_yellow_0, axiom,  (! [A] :  (l1_orders_2(A) =>  (! [B] :  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (r2_yellow_0(A, B) =>  (C=k2_yellow_0(A, B) <=>  (r1_lattice3(A, B, C) &  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (r1_lattice3(A, B, D) => r1_orders_2(A, D, C)) ) ) ) ) ) ) ) ) ) ) ).
fof(d15_lattice3, axiom,  (! [A] :  (l1_orders_2(A) =>  ( (v3_orders_2(A) &  (v4_orders_2(A) &  (v5_orders_2(A) &  (v1_lattice3(A) &  (v2_lattice3(A) & l1_orders_2(A)) ) ) ) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  &  (v3_lattices(B) &  (v10_lattices(B) & l3_lattices(B)) ) )  =>  (B=k14_lattice3(A) <=> g1_orders_2(u1_struct_0(A), u1_orders_2(A))=k3_lattice3(B)) ) ) ) ) ) ).
fof(d4_yellow_0, axiom,  (! [A] :  (l1_orders_2(A) =>  (v1_yellow_0(A) <=>  (? [B] :  (m1_subset_1(B, u1_struct_0(A)) & r1_lattice3(A, u1_struct_0(A), B)) ) ) ) ) ).
fof(d5_yellow_0, axiom,  (! [A] :  (l1_orders_2(A) =>  (v2_yellow_0(A) <=>  (? [B] :  (m1_subset_1(B, u1_struct_0(A)) & r2_lattice3(A, u1_struct_0(A), B)) ) ) ) ) ).
fof(d7_yellow_0, axiom,  (! [A] :  (l1_orders_2(A) =>  (! [B] :  (r1_yellow_0(A, B) <=>  (? [C] :  (m1_subset_1(C, u1_struct_0(A)) &  (r2_lattice3(A, B, C) &  ( (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (r2_lattice3(A, B, D) => r1_orders_2(A, C, D)) ) )  &  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  ( (r2_lattice3(A, B, D) &  (! [E] :  (m1_subset_1(E, u1_struct_0(A)) =>  (r2_lattice3(A, B, E) => r1_orders_2(A, D, E)) ) ) )  => D=C) ) ) ) ) ) ) ) ) ) ) ).
fof(d8_yellow_0, axiom,  (! [A] :  (l1_orders_2(A) =>  (! [B] :  (r2_yellow_0(A, B) <=>  (? [C] :  (m1_subset_1(C, u1_struct_0(A)) &  (r1_lattice3(A, B, C) &  ( (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (r1_lattice3(A, B, D) => r1_orders_2(A, D, C)) ) )  &  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  ( (r1_lattice3(A, B, D) &  (! [E] :  (m1_subset_1(E, u1_struct_0(A)) =>  (r1_lattice3(A, B, E) => r1_orders_2(A, E, D)) ) ) )  => D=C) ) ) ) ) ) ) ) ) ) ) ).
fof(d9_yellow_0, axiom,  (! [A] :  (l1_orders_2(A) =>  (! [B] :  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (r1_yellow_0(A, B) =>  (C=k1_yellow_0(A, B) <=>  (r2_lattice3(A, B, C) &  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (r2_lattice3(A, B, D) => r1_orders_2(A, C, D)) ) ) ) ) ) ) ) ) ) ) ).
fof(dt_k14_lattice3, axiom,  (! [A] :  (l1_orders_2(A) =>  ( ~ (v2_struct_0(k14_lattice3(A)))  &  (v3_lattices(k14_lattice3(A)) &  (v10_lattices(k14_lattice3(A)) & l3_lattices(k14_lattice3(A))) ) ) ) ) ).
fof(dt_k1_yellow_0, axiom,  (! [A, B] :  (l1_orders_2(A) => m1_subset_1(k1_yellow_0(A, B), u1_struct_0(A))) ) ).
fof(dt_k2_yellow_0, axiom,  (! [A, B] :  (l1_orders_2(A) => m1_subset_1(k2_yellow_0(A, B), u1_struct_0(A))) ) ).
fof(fc8_lattice3, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v3_orders_2(A) &  (v4_orders_2(A) &  (v5_orders_2(A) &  (v3_lattice3(A) & l1_orders_2(A)) ) ) ) )  =>  ( ~ (v2_struct_0(k14_lattice3(A)))  &  (v3_lattices(k14_lattice3(A)) &  (v10_lattices(k14_lattice3(A)) & v4_lattice3(k14_lattice3(A))) ) ) ) ) ).
fof(fraenkel_a_2_0_yellow_0, axiom,  (! [A, B, C] :  ( ( ~ (v2_struct_0(B))  &  (v5_orders_2(B) &  (v3_lattice3(B) & l1_orders_2(B)) ) )  =>  (r2_hidden(A, a_2_0_yellow_0(B, C)) <=>  (? [D] :  (m1_subset_1(D, u1_struct_0(B)) &  (A=D & r1_lattice3(B, C, D)) ) ) ) ) ) ).
fof(rc1_lattice3, axiom,  (? [A] :  (l1_orders_2(A) &  ( ~ (v2_struct_0(A))  &  (v1_orders_2(A) &  (v2_orders_2(A) &  (v3_orders_2(A) &  (v4_orders_2(A) &  (v5_orders_2(A) & v3_lattice3(A)) ) ) ) ) ) ) ) ).
fof(rc1_yellow_0, axiom,  (? [A] :  (l1_orders_2(A) &  ( ~ (v2_struct_0(A))  &  (v7_struct_0(A) &  (v1_orders_2(A) & v3_orders_2(A)) ) ) ) ) ).
fof(rc2_lattice3, axiom,  (? [A] :  (l1_orders_2(A) &  ( ~ (v2_struct_0(A))  &  (v1_orders_2(A) &  (v2_orders_2(A) &  (v3_orders_2(A) &  (v4_orders_2(A) &  (v5_orders_2(A) &  (v1_lattice3(A) &  (v2_lattice3(A) & v3_lattice3(A)) ) ) ) ) ) ) ) ) ) ).
fof(rc2_yellow_0, axiom,  (? [A] :  (l1_orders_2(A) &  ( ~ (v2_struct_0(A))  &  (v2_orders_2(A) &  (v3_orders_2(A) &  (v4_orders_2(A) &  (v5_orders_2(A) & v3_lattice3(A)) ) ) ) ) ) ) ).
fof(t10_yellow_0, axiom,  (! [A] :  (l1_orders_2(A) =>  (! [B] :  (! [C] :  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  ( ( (r1_lattice3(A, B, D) & r1_lattice3(A, C, D))  => r1_lattice3(A, k2_xboole_0(B, C), D))  &  ( (r2_lattice3(A, B, D) & r2_lattice3(A, C, D))  => r2_lattice3(A, k2_xboole_0(B, C), D)) ) ) ) ) ) ) ) ).
fof(t11_yellow_0, axiom,  (! [A] :  ( (v4_orders_2(A) & l1_orders_2(A))  =>  (! [B] :  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  ( (r2_lattice3(A, B, C) & r1_orders_2(A, C, D))  => r2_lattice3(A, B, D)) ) ) ) ) ) ) ) ).
fof(t12_yellow_0, axiom,  (! [A] :  ( (v4_orders_2(A) & l1_orders_2(A))  =>  (! [B] :  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  ( (r1_lattice3(A, B, C) & r1_orders_2(A, D, C))  => r1_lattice3(A, B, D)) ) ) ) ) ) ) ) ).
fof(t13_yellow_0, axiom,  (! [A] :  (l1_orders_2(A) =>  (! [B] :  (l1_orders_2(B) =>  (g1_orders_2(u1_struct_0(A), u1_orders_2(A))=g1_orders_2(u1_struct_0(B), u1_orders_2(B)) =>  ( (v1_yellow_0(A) => v1_yellow_0(B))  &  (v2_yellow_0(A) => v2_yellow_0(B)) ) ) ) ) ) ) ).
fof(t14_yellow_0, axiom,  (! [A] :  (l1_orders_2(A) =>  (! [B] :  (l1_orders_2(B) =>  (g1_orders_2(u1_struct_0(A), u1_orders_2(A))=g1_orders_2(u1_struct_0(B), u1_orders_2(B)) =>  (! [C] :  ( (r1_yellow_0(A, C) => r1_yellow_0(B, C))  &  (r2_yellow_0(A, C) => r2_yellow_0(B, C)) ) ) ) ) ) ) ) ).
fof(t15_yellow_0, axiom,  (! [A] :  ( (v5_orders_2(A) & l1_orders_2(A))  =>  (! [B] :  (r1_yellow_0(A, B) <=>  (? [C] :  (m1_subset_1(C, u1_struct_0(A)) &  (r2_lattice3(A, B, C) &  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (r2_lattice3(A, B, D) => r1_orders_2(A, C, D)) ) ) ) ) ) ) ) ) ) ).
fof(t16_yellow_0, axiom,  (! [A] :  ( (v5_orders_2(A) & l1_orders_2(A))  =>  (! [B] :  (r2_yellow_0(A, B) <=>  (? [C] :  (m1_subset_1(C, u1_struct_0(A)) &  (r1_lattice3(A, B, C) &  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (r1_lattice3(A, B, D) => r1_orders_2(A, D, C)) ) ) ) ) ) ) ) ) ) ).
fof(t17_yellow_0, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v5_orders_2(A) &  (v3_lattice3(A) & l1_orders_2(A)) ) )  =>  (! [B] :  (r1_yellow_0(A, B) & r2_yellow_0(A, B)) ) ) ) ).
fof(t18_yellow_0, axiom,  (! [A] :  ( (v5_orders_2(A) & l1_orders_2(A))  =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  ( ( (D=k10_lattice3(A, B, C) & r1_yellow_0(A, k2_tarski(B, C)))  =>  (r1_orders_2(A, B, D) &  (r1_orders_2(A, C, D) &  (! [E] :  (m1_subset_1(E, u1_struct_0(A)) =>  ( (r1_orders_2(A, B, E) & r1_orders_2(A, C, E))  => r1_orders_2(A, D, E)) ) ) ) ) )  &  ( (r1_orders_2(A, B, D) &  (r1_orders_2(A, C, D) &  (! [E] :  (m1_subset_1(E, u1_struct_0(A)) =>  ( (r1_orders_2(A, B, E) & r1_orders_2(A, C, E))  => r1_orders_2(A, D, E)) ) ) ) )  =>  (D=k10_lattice3(A, B, C) & r1_yellow_0(A, k2_tarski(B, C))) ) ) ) ) ) ) ) ) ) ) ).
fof(t19_yellow_0, axiom,  (! [A] :  ( (v5_orders_2(A) & l1_orders_2(A))  =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  ( ( (D=k11_lattice3(A, B, C) & r2_yellow_0(A, k2_tarski(B, C)))  =>  (r1_orders_2(A, D, B) &  (r1_orders_2(A, D, C) &  (! [E] :  (m1_subset_1(E, u1_struct_0(A)) =>  ( (r1_orders_2(A, E, B) & r1_orders_2(A, E, C))  => r1_orders_2(A, E, D)) ) ) ) ) )  &  ( (r1_orders_2(A, D, B) &  (r1_orders_2(A, D, C) &  (! [E] :  (m1_subset_1(E, u1_struct_0(A)) =>  ( (r1_orders_2(A, E, B) & r1_orders_2(A, E, C))  => r1_orders_2(A, E, D)) ) ) ) )  =>  (D=k11_lattice3(A, B, C) & r2_yellow_0(A, k2_tarski(B, C))) ) ) ) ) ) ) ) ) ) ) ).
fof(t1_yellow_0, axiom,  (! [A] :  (l1_orders_2(A) =>  (! [B] :  (l1_orders_2(B) =>  (g1_orders_2(u1_struct_0(A), u1_orders_2(A))=g1_orders_2(u1_struct_0(B), u1_orders_2(B)) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (! [E] :  (m1_subset_1(E, u1_struct_0(B)) =>  (! [F] :  (m1_subset_1(F, u1_struct_0(B)) =>  ( (C=E & D=F)  =>  ( (r1_orders_2(A, C, D) => r1_orders_2(B, E, F))  &  (r2_orders_2(A, C, D) => r2_orders_2(B, E, F)) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(t20_yellow_0, axiom,  (! [A] :  ( (v5_orders_2(A) & l1_orders_2(A))  =>  (v1_lattice3(A) <=>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) => r1_yellow_0(A, k2_tarski(B, C))) ) ) ) ) ) ) ).
fof(t21_yellow_0, axiom,  (! [A] :  ( (v5_orders_2(A) & l1_orders_2(A))  =>  (v2_lattice3(A) <=>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) => r2_yellow_0(A, k2_tarski(B, C))) ) ) ) ) ) ) ).
fof(t22_yellow_0, axiom,  (! [A] :  ( (v5_orders_2(A) &  (v1_lattice3(A) & l1_orders_2(A)) )  =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (D=k13_lattice3(A, B, C) <=>  (r1_orders_2(A, B, D) &  (r1_orders_2(A, C, D) &  (! [E] :  (m1_subset_1(E, u1_struct_0(A)) =>  ( (r1_orders_2(A, B, E) & r1_orders_2(A, C, E))  => r1_orders_2(A, D, E)) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(t23_yellow_0, axiom,  (! [A] :  ( (v5_orders_2(A) &  (v2_lattice3(A) & l1_orders_2(A)) )  =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (D=k12_lattice3(A, B, C) <=>  (r1_orders_2(A, D, B) &  (r1_orders_2(A, D, C) &  (! [E] :  (m1_subset_1(E, u1_struct_0(A)) =>  ( (r1_orders_2(A, E, B) & r1_orders_2(A, E, C))  => r1_orders_2(A, E, D)) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(t24_yellow_0, axiom,  (! [A] :  ( (v3_orders_2(A) &  (v5_orders_2(A) &  (v1_lattice3(A) & l1_orders_2(A)) ) )  =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (B=k13_lattice3(A, B, C) <=> r1_orders_2(A, C, B)) ) ) ) ) ) ) ).
fof(t25_yellow_0, axiom,  (! [A] :  ( (v3_orders_2(A) &  (v5_orders_2(A) &  (v2_lattice3(A) & l1_orders_2(A)) ) )  =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (B=k12_lattice3(A, B, C) <=> r3_orders_2(A, B, C)) ) ) ) ) ) ) ).
fof(t26_yellow_0, axiom,  (! [A] :  (l1_orders_2(A) =>  (! [B] :  (l1_orders_2(B) =>  (g1_orders_2(u1_struct_0(A), u1_orders_2(A))=g1_orders_2(u1_struct_0(B), u1_orders_2(B)) =>  (! [C] :  (r1_yellow_0(A, C) => k1_yellow_0(A, C)=k1_yellow_0(B, C)) ) ) ) ) ) ) ).
fof(t27_yellow_0, axiom,  (! [A] :  (l1_orders_2(A) =>  (! [B] :  (l1_orders_2(B) =>  (g1_orders_2(u1_struct_0(A), u1_orders_2(A))=g1_orders_2(u1_struct_0(B), u1_orders_2(B)) =>  (! [C] :  (r2_yellow_0(A, C) => k2_yellow_0(A, C)=k2_yellow_0(B, C)) ) ) ) ) ) ) ).
fof(t28_yellow_0, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v3_orders_2(A) &  (v4_orders_2(A) &  (v5_orders_2(A) &  (v3_lattice3(A) & l1_orders_2(A)) ) ) ) )  =>  (! [B] :  (k1_yellow_0(A, B)=k15_lattice3(k14_lattice3(A), B) & k2_yellow_0(A, B)=k16_lattice3(k14_lattice3(A), B)) ) ) ) ).
fof(t29_yellow_0, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v10_lattices(A) &  (v4_lattice3(A) & l3_lattices(A)) ) )  =>  (! [B] :  (k15_lattice3(A, B)=k1_yellow_0(k3_lattice3(A), B) & k16_lattice3(A, B)=k2_yellow_0(k3_lattice3(A), B)) ) ) ) ).
fof(t2_yellow_0, axiom,  (! [A] :  (l1_orders_2(A) =>  (! [B] :  (l1_orders_2(B) =>  (g1_orders_2(u1_struct_0(A), u1_orders_2(A))=g1_orders_2(u1_struct_0(B), u1_orders_2(B)) =>  (! [C] :  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (! [E] :  (m1_subset_1(E, u1_struct_0(B)) =>  (D=E =>  ( (r2_lattice3(A, C, D) => r2_lattice3(B, C, E))  &  (r1_lattice3(A, C, D) => r1_lattice3(B, C, E)) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(t30_yellow_0, axiom,  (! [A] :  ( (v5_orders_2(A) & l1_orders_2(A))  =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  ( ( (B=k1_yellow_0(A, C) & r1_yellow_0(A, C))  =>  (r2_lattice3(A, C, B) &  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (r2_lattice3(A, C, D) => r1_orders_2(A, B, D)) ) ) ) )  &  ( (r2_lattice3(A, C, B) &  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (r2_lattice3(A, C, D) => r1_orders_2(A, B, D)) ) ) )  =>  (B=k1_yellow_0(A, C) & r1_yellow_0(A, C)) ) ) ) ) ) ) ) ).
fof(t31_yellow_0, axiom,  (! [A] :  ( (v5_orders_2(A) & l1_orders_2(A))  =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  ( ( (B=k2_yellow_0(A, C) & r2_yellow_0(A, C))  =>  (r1_lattice3(A, C, B) &  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (r1_lattice3(A, C, D) => r1_orders_2(A, D, B)) ) ) ) )  &  ( (r1_lattice3(A, C, B) &  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (r1_lattice3(A, C, D) => r1_orders_2(A, D, B)) ) ) )  =>  (B=k2_yellow_0(A, C) & r2_yellow_0(A, C)) ) ) ) ) ) ) ) ).
fof(t32_yellow_0, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v5_orders_2(A) &  (v3_lattice3(A) & l1_orders_2(A)) ) )  =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (B=k1_yellow_0(A, C) <=>  (r2_lattice3(A, C, B) &  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (r2_lattice3(A, C, D) => r1_orders_2(A, B, D)) ) ) ) ) ) ) ) ) ) ).
fof(t33_yellow_0, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v5_orders_2(A) &  (v3_lattice3(A) & l1_orders_2(A)) ) )  =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (B=k2_yellow_0(A, C) <=>  (r1_lattice3(A, C, B) &  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (r1_lattice3(A, C, D) => r1_orders_2(A, D, B)) ) ) ) ) ) ) ) ) ) ).
fof(t34_yellow_0, axiom,  (! [A] :  (l1_orders_2(A) =>  (! [B] :  (! [C] :  ( (r1_tarski(B, C) &  (r1_yellow_0(A, B) & r1_yellow_0(A, C)) )  => r1_orders_2(A, k1_yellow_0(A, B), k1_yellow_0(A, C))) ) ) ) ) ).
fof(t35_yellow_0, axiom,  (! [A] :  (l1_orders_2(A) =>  (! [B] :  (! [C] :  ( (r1_tarski(B, C) &  (r2_yellow_0(A, B) & r2_yellow_0(A, C)) )  => r1_orders_2(A, k2_yellow_0(A, C), k2_yellow_0(A, B))) ) ) ) ) ).
fof(t36_yellow_0, axiom,  (! [A] :  ( (v4_orders_2(A) &  (v5_orders_2(A) & l1_orders_2(A)) )  =>  (! [B] :  (! [C] :  ( (r1_yellow_0(A, B) &  (r1_yellow_0(A, C) & r1_yellow_0(A, k2_xboole_0(B, C))) )  => k1_yellow_0(A, k2_xboole_0(B, C))=k10_lattice3(A, k1_yellow_0(A, B), k1_yellow_0(A, C))) ) ) ) ) ).
fof(t37_yellow_0, axiom,  (! [A] :  ( (v4_orders_2(A) &  (v5_orders_2(A) & l1_orders_2(A)) )  =>  (! [B] :  (! [C] :  ( (r2_yellow_0(A, B) &  (r2_yellow_0(A, C) & r2_yellow_0(A, k2_xboole_0(B, C))) )  => k2_yellow_0(A, k2_xboole_0(B, C))=k11_lattice3(A, k2_yellow_0(A, B), k2_yellow_0(A, C))) ) ) ) ) ).
fof(t38_yellow_0, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v3_orders_2(A) &  (v5_orders_2(A) & l1_orders_2(A)) ) )  =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (r1_yellow_0(A, k6_domain_1(u1_struct_0(A), B)) & r2_yellow_0(A, k6_domain_1(u1_struct_0(A), B))) ) ) ) ) ).
fof(t39_yellow_0, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v3_orders_2(A) &  (v5_orders_2(A) & l1_orders_2(A)) ) )  =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (k1_yellow_0(A, k6_domain_1(u1_struct_0(A), B))=B & k2_yellow_0(A, k6_domain_1(u1_struct_0(A), B))=B) ) ) ) ) ).
fof(t3_yellow_0, axiom,  (! [A] :  (l1_orders_2(A) =>  (! [B] :  (l1_orders_2(B) =>  ( (g1_orders_2(u1_struct_0(A), u1_orders_2(A))=g1_orders_2(u1_struct_0(B), u1_orders_2(B)) & v3_lattice3(A))  => v3_lattice3(B)) ) ) ) ) ).
fof(t40_yellow_0, axiom,  (! [A] :  ( (v3_orders_2(A) &  (v4_orders_2(A) &  (v5_orders_2(A) &  (v2_lattice3(A) & l1_orders_2(A)) ) ) )  =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) => k2_yellow_0(A, k7_domain_1(u1_struct_0(A), B, C))=k12_lattice3(A, B, C)) ) ) ) ) ) ).
fof(t41_yellow_0, axiom,  (! [A] :  ( (v3_orders_2(A) &  (v4_orders_2(A) &  (v5_orders_2(A) &  (v1_lattice3(A) & l1_orders_2(A)) ) ) )  =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) => k1_yellow_0(A, k7_domain_1(u1_struct_0(A), B, C))=k13_lattice3(A, B, C)) ) ) ) ) ) ).
fof(t42_yellow_0, conjecture,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v5_orders_2(A) &  (v1_yellow_0(A) & l1_orders_2(A)) ) )  =>  (r1_yellow_0(A, k1_xboole_0) & r2_yellow_0(A, u1_struct_0(A))) ) ) ).
fof(t4_yellow_0, axiom,  (! [A] :  ( (v4_orders_2(A) & l1_orders_2(A))  =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (r1_orders_2(A, B, C) =>  (! [D] :  ( (r1_lattice3(A, D, C) => r1_lattice3(A, D, B))  &  (r2_lattice3(A, D, B) => r2_lattice3(A, D, C)) ) ) ) ) ) ) ) ) ) ).
fof(t5_yellow_0, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l1_orders_2(A))  =>  (! [B] :  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  ( (r2_lattice3(A, B, C) => r2_lattice3(A, k3_xboole_0(B, u1_struct_0(A)), C))  &  ( (r2_lattice3(A, k3_xboole_0(B, u1_struct_0(A)), C) => r2_lattice3(A, B, C))  &  ( (r1_lattice3(A, B, C) => r1_lattice3(A, k3_xboole_0(B, u1_struct_0(A)), C))  &  (r1_lattice3(A, k3_xboole_0(B, u1_struct_0(A)), C) => r1_lattice3(A, B, C)) ) ) ) ) ) ) ) ) ).
fof(t6_yellow_0, axiom,  (! [A] :  (l1_orders_2(A) =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (r2_lattice3(A, k1_xboole_0, B) & r1_lattice3(A, k1_xboole_0, B)) ) ) ) ) ).
fof(t7_yellow_0, axiom,  (! [A] :  (l1_orders_2(A) =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  ( (r1_lattice3(A, k1_tarski(C), B) => r1_orders_2(A, B, C))  &  ( (r1_orders_2(A, B, C) => r1_lattice3(A, k1_tarski(C), B))  &  ( (r2_lattice3(A, k1_tarski(C), B) => r1_orders_2(A, C, B))  &  (r1_orders_2(A, C, B) => r2_lattice3(A, k1_tarski(C), B)) ) ) ) ) ) ) ) ) ) ).
fof(t8_yellow_0, axiom,  (! [A] :  (l1_orders_2(A) =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  ( (r1_lattice3(A, k2_tarski(C, D), B) =>  (r1_orders_2(A, B, C) & r1_orders_2(A, B, D)) )  &  ( ( (r1_orders_2(A, B, C) & r1_orders_2(A, B, D))  => r1_lattice3(A, k2_tarski(C, D), B))  &  ( (r2_lattice3(A, k2_tarski(C, D), B) =>  (r1_orders_2(A, C, B) & r1_orders_2(A, D, B)) )  &  ( (r1_orders_2(A, C, B) & r1_orders_2(A, D, B))  => r2_lattice3(A, k2_tarski(C, D), B)) ) ) ) ) ) ) ) ) ) ) ) ).
fof(t9_yellow_0, axiom,  (! [A] :  (l1_orders_2(A) =>  (! [B] :  (! [C] :  (r1_tarski(B, C) =>  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  ( (r1_lattice3(A, C, D) => r1_lattice3(A, B, D))  &  (r2_lattice3(A, C, D) => r2_lattice3(A, B, D)) ) ) ) ) ) ) ) ) ).
